	///////////////////////////////////////////////////////////////////////////////
	// Building Supplies
	///////////////////////////////////////////////////////////////////////////////
	//class Exile_Item_WoodDrawBridgeKit					{ quality = 1; price = 750; };
	class Exile_Item_ConcreteDoorwayKit					{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteDrawBridgeKit         		{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteFloorKit           		{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteFloorPortKit       		{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteFloorPortSmallKit         	{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteGateKit            		{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteLadderHatchKit         	{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteStairsKit          		{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteSupportKit         		{ quality = 3; price = 2200; };
	class Exile_Item_ConcreteWallKit            		{ quality = 3; price = 2200; };
	class Exile_Item_MetalHedgehogKit					{ quality = 2; price = 1200; };
	class Exile_Item_MetalLadderDoubleKit				{ quality = 2; price = 1200; };
	class Exile_Item_MetalLadderKit						{ quality = 2; price = 600; };
	class Exile_Item_OldChestKit						{ quality = 1; price = 500; };
	class Exile_Item_WoodDoorKit						{ quality = 2; price = 750; };
	class Exile_Item_WoodDoorwayKit						{ quality = 2; price = 750; };
	class Exile_Item_WoodFloorKit						{ quality = 2; price = 750; };
	class Exile_Item_WoodFloorPortKit					{ quality = 2; price = 750; };
	class Exile_Item_WoodGateKit						{ quality = 2; price = 750; };
	class Exile_Item_WoodLadderHatchKit					{ quality = 2; price = 750; };
	class Exile_Item_WoodStairsKit						{ quality = 2; price = 750; };
	class Exile_Item_WoodSupportKit						{ quality = 2; price = 500; };
	class Exile_Item_WoodWallHalfKit					{ quality = 2; price = 500; };
	class Exile_Item_WoodWallKit						{ quality = 2; price = 750; };
	class Exile_Item_WoodWindowKit						{ quality = 2; price = 750; };
	class Exile_Item_WorkBenchKit						{ quality = 2; price = 500; };	
	
	////////////////////////////////////////////////////////////////////////////////
	//DDR Items
	///////////////////////////////////////////////////////////////////////////////
	class DDR_Item_Antibiotic { quality = 1; price = 150;};
	class DDR_Item_Bloodbag { quality = 3; price = 2500;};
	class DDR_Item_Bucket { quality = 1; price = 20;};
	class DDR_Item_Bandage_Dirty { quality = 1; price = 100;};
	class DDR_Item_Dressing { quality = 1; price = 200;};
	class DDR_Item_Firstaid { quality = 4; price = 3000;};
	class DDR_Item_Painkillers { quality = 2; price = 200;};
	class DDR_Item_Vitamins { quality = 1; price = 100;};
	class DDR_Item_Bakedbeans { quality = 1; price = 100;};
	class DDR_Item_Bakedbeans_Cooked { quality = 1; price = 200;};
	class DDR_Item_Canteen_Coffee_Milk { quality = 2; price = 500;};
	class DDR_Item_PlasticBottleCoffee_Milk { quality = 1; price = 5000;};
	class DDR_Item_Canteen_Coffee { quality = 2; price = 500;};
	class DDR_Item_Canteen_Fresh { quality = 1; price = 450;};
	class DDR_Item_Canteen { quality = 1; price = 50;};
	class DDR_Item_Canteen_Dirty { quality = 1; price = 100;};
	class DDR_Item_Canteen_Salt { quality = 1; price = 100;};
	class DDR_Item_Cereal_Crunchin { quality = 1; price = 150;};
	class DDR_Item_Franta { quality = 2; price = 150;};
	class DDR_Item_Orange { quality = 1; price = 100;};
	class DDR_Item_Milkpowder { quality = 1; price = 50;};
	class DDR_Item_Pumpkin { quality = 2; price = 400;};
	class DDR_Item_Purificationtablets { quality = 1; price = 20;};
	class DDR_Item_Redgull { quality = 2; price = 200;};
	class DDR_Item_Rice { quality = 2; price = 450;};
	class DDR_Item_Rice_Cooked { quality = 2; price = 500;};
	class DDR_Item_Spirit { quality = 1; price = 350;};
	class DDR_Item_Tacticalbacon_Cooked { quality = 2; price = 400;};
	class DDR_Item_Tacticalbacon { quality = 2; price = 300;};
	class DDR_Item_Salema { quality = 1; price = 5000;};
	class DDR_Item_Mackerel { quality = 1; price = 100;};
	class DDR_Item_Tunaa { quality = 2; price = 250;};
	class DDR_Item_Mullet { quality = 1; price = 100;};
	class DDR_Item_CatShark { quality = 2; price = 200;};
	class DDR_Item_Ornate { quality = 1; price = 100;};
	class DDR_Item_Turtle { quality = 1; price = 200;};
	class DDR_Item_Money { quality = 1; price = 1000; sellPrice = 1000;};
	class DDR_Item_Battery { quality = 1; price = 20;};
	class DDR_Item_Container { quality = 1; price = 20;};
	class DDR_Item_Container_Soup { quality = 3; price = 500;};
	class DDR_Item_Container_Chicken_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Alsatian_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_CatShark_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Fin_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Goat_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Mackerel_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Mullet_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Ornate_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Rabbit_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Rooster_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Salema_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Sheep_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Snake_Rice { quality = 3; price = 5000;};
	class DDR_Item_Container_Tuna_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Turtle_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Salemaa_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Mackerell_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Tunaa_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Mullett_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_CatSharkk_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Ornatee_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Turtlee_Rice { quality = 3; price = 500;};
	class DDR_Item_Container_Chicken_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Alsatian_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_CatShark_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Fin_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Goat_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Mackerel_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Mullet_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Ornate_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Rabbit_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Rooster_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Salema_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Sheep_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Snake_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Tuna_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Turtle_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Salemaa_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Mackerell_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Tunaa_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Mullett_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_CatSharkk_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Ornatee_Potato { quality = 3; price = 500;};
	class DDR_Item_Container_Turtlee_Potato { quality = 3; price = 500;};
	class DDR_Item_Measuring_Tape { quality = 1; price = 5000;};
	class DDR_Item_Cinder_Block { quality = 1; price = 20;};
	class DDR_Item_Injector { quality = 1; price = 50;};
	class DDR_Item_Pop_Tabs_Bag { quality = 1; price = 2000; sellPrice = 1000;};
	class DDR_Item_Main_Rotor { quality = 1; price = 200;};
	class DDR_Item_Apple_Red { quality = 1; price = 100;};
	class DDR_Item_Apple { quality = 1; price = 100;};
	class DDR_Item_Apple_Green { quality = 1; price = 100;};
	class DDR_Item_Blueberry { quality = 1; price = 50;};
	class DDR_Item_Rottenberry { quality = 1; price = 20;};
	class DDR_Item_Redberry { quality = 1; price = 50;};
	class DDR_Item_Banana { quality = 1; price = 50;};
	class DDR_Item_Pear { quality = 1; price = 50;};
	class DDR_Item_Tomato { quality = 1; price = 50;};
	class DDR_Item_Strawberry { quality = 1; price = 50;};
	class DDR_Item_Coke { quality = 1; price = 200;};
	class DDR_Item_Jackoff { quality = 2; price = 200;};
	class DDR_Item_Rotten_Orange { quality = 1; price = 20;};
	class DDR_Item_Rotten_Apple { quality = 1; price = 20;};
	class DDR_Item_Rotten_Apricot { quality = 1; price = 20;};
	class DDR_Item_Hamburger { quality = 1; price = 150;};
	class DDR_Item_Yummy_Juice { quality = 1; price = 150;};
	class DDR_Item_Potato { quality = 1; price = 100;};
	class DDR_Item_Melon { quality = 1; price = 100;};
	class DDR_Item_Beet { quality = 1; price = 100;};
	class DDR_Item_Bread { quality = 1; price = 100;};
	class DDR_Item_Bread_Roll { quality = 1; price = 1000;};
	class DDR_Item_Passion_Fruit { quality = 1; price = 100;};
	class DDR_Item_Pomegranate { quality = 1; price = 100;};
	class DDR_Item_Rotten_Pear { quality = 1; price = 20;};
	class DDR_Item_Rotten_Melon { quality = 1; price = 20;};
	class DDR_Item_Tailrotor { quality = 1; price = 20;};
	class DDR_Item_Rotten_Banana { quality = 1; price = 20;};
	class DDR_Item_Cucumber { quality = 1; price = 100;};
	class DDR_Item_Pan { quality = 1; price = 20;};
	class DDR_Item_Glass { quality = 1; price = 20;};
	class DDR_Item_Fiberglass { quality = 1; price = 200;};
	class DDR_Item_Engine { quality = 1; price = 200;};
	class DDR_Item_Pineapple { quality = 1; price = 150;};
	class DDR_Item_Electrical_Component { quality = 1; price = 200;};
	class DDR_Item_Stones { quality = 1; price = 20;};
	class DDR_Item_Wood_Sticks { quality = 1; price = 20;};
	class DDR_Item_Leaves { quality = 1; price = 20;};
	class DDR_Item_Silver_Bar { quality = 2; price = 5000; sellPrice = 2500;};
	class DDR_Item_Gold_Bar { quality = 2; price = 10000; sellPrice = 5000;};
	class DDR_Item_Silver_Ore { quality = 1; price = 500;};
	class DDR_Item_Gold_Ore { quality = 2; price = 1000;};
	class DDR_Item_Carrot { quality = 1; price = 75;};
	class DDR_Item_Rotten_Carrot { quality = 1; price = 20;};
	class DDR_Item_Salt_Shaker { quality = 1; price = 20;};
	class DDR_Item_Pepper_Shaker { quality = 1; price = 20;};
	class DDR_Item_Old_Pot { quality = 1; price = 20;};
	class DDR_Item_Pickaxe { quality = 1; price = 20;};
	class DDR_Item_Mushrooms { quality = 1; price = 200;};
	class DDR_Item_Drugs_Cocaine { quality = 3; price = 500;};
	class DDR_Item_Drugs_Weed { quality = 3; price = 520;};
	class DDR_Item_Heroin { quality = 1; price = 5000;};
	class DDR_Item_Disinfectant { quality = 1; price = 20;};
	class DDR_Item_Disinfectant_not_scripted { quality = 1; price = 20;};
	class DDR_Item_Craft_Box { quality = 1; price = 20;};
	class DDR_Item_Crystal_Purple { quality = 1; price = 220;};
	class DDR_Item_Crystal_Green { quality = 1; price = 300;};
	class DDR_Item_Gemstone_Red { quality = 1; price = 150;};
	class DDR_Item_Gemstone_Blue { quality = 1; price = 250;};
	class DDR_Item_Diamond_Purple { quality = 1; price = 200;};
	class DDR_Item_Diamond_Green { quality = 1; price = 200;};
	class DDR_Item_Diamond_Yellow { quality = 1; price = 500;};
	class DDR_Item_Diamond_Sky_Blue { quality = 1; price = 200;};
	class DDR_Item_Diamond_Red { quality = 1; price = 400;};
	class DDR_Item_Diamond_Blue { quality = 1; price = 200;};
	class DDR_Item_Fishing_Net { quality = 1; price = 20;};
	class DDR_Item_Skull { quality = 1; price = 20;};
	class DDR_Item_Old_Documents { quality = 1; price = 20;};
	class DDR_Item_Old_Camera { quality = 1; price = 20;};