/**
 * English and French comments
 * Commentaires anglais et français
 *
 * This file is a template to add objetcs from an addon in the configuration variables of the logistics system.
 * Make a copy of this file and fill it. Then add a #include to this file in the file R3F_LOG\config.sqf.
 *
 * IMPORTANT NOTE : when a logistics feature is given to an object/vehicle class name, all the classes which inherit
 *                  of the parent/generic class (according to the CfgVehicles) will also have this feature.
 *                  CfgVehicles tree view example : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 *
 *
 * Ce fichier est un exemple vierge permettant d'ajouter des objets d'un addon dans la configuration du système de logistique.
 * Faites une copie de ce fichier et remplissez-le. Puis ajouter un #include vers celui-ci dans le fichier R3F_LOG\config.sqf.
 *
 * NOTE IMPORTANTE : lorsqu'une fonctionnalité logistique est accordée à un nom de classe d'objet/véhicule, les classes
 *                   héritant de cette classe mère/générique (selon le CfgVehicles) se verront également dotées de cette fonctionnalité.
 *                   Exemple d'arborescence du CfgVehicles : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 */

/**
 * List of class names of ground vehicles which can tow objects.
 * Liste des noms de classes des véhicules terrestres pouvant remorquer des objets.
 */
R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
	// e.g. : "MyTowingVehicleClassName1", "MyTowingVehicleClassName2"

			"B_G_Offroad_01_F",
			"B_G_Offroad_01_repair_F",
			"B_G_Quadbike_01_F",
			"B_MRAP_01_F",
			"B_Quadbike_01_F",
			"C_Hatchback_01_F",
			"C_Hatchback_01_beigecustom_F",
			"C_Hatchback_01_black_F",
			"C_Hatchback_01_blue_F",
			"C_Hatchback_01_bluecustom_F",
			"C_Hatchback_01_dark_F",
			"C_Hatchback_01_green_F",
			"C_Hatchback_01_grey_F",
			"C_Hatchback_01_sport_F",
			"C_Hatchback_01_sport_blue_F",
			"C_Hatchback_01_sport_green_F",
			"C_Hatchback_01_sport_grey_F",
			"C_Hatchback_01_sport_orange_F",
			"C_Hatchback_01_sport_red_F",
			"C_Hatchback_01_sport_white_F",
			"C_Hatchback_01_white_F",
			"C_Hatchback_01_yellow_F",
			"C_Kart_01_Blu_F",
			"C_Kart_01_F",
			"C_Kart_01_Fuel_F",
			"C_Kart_01_Red_F",
			"C_Kart_01_Vrana_F",
			"C_Kart_01_black_F",
			"C_Kart_01_green_F",
			"C_Kart_01_orange_F",
			"C_Kart_01_white_F",
			"C_Kart_01_yellow_F",
			"C_Offroad_01_F",
			"C_Offroad_01_blue_F",
			"C_Offroad_01_bluecustom_F",
			"C_Offroad_01_darkred_F",
			"C_Offroad_01_red_F",
			"C_Offroad_01_repair_F",
			"C_Offroad_01_sand_F",
			"C_Offroad_01_white_F",
			"C_Offroad_default_F",
			"C_Offroad_luxe_F",
			"C_Offroad_stripped_F",		
			"I_G_Offroad_01_F",
			"C_SUV_01_F",
			"C_IDAP_Offroad_01_F",
			"C_IDAP_Offroad_02_unarmed_F",
			"O_G_Offroad_01_F",
			"C_Quadbike_01_F",
			"C_Quadbike_01_black_F",
			"C_Quadbike_01_blue_F",
			"C_Quadbike_01_red_F",
			"C_Quadbike_01_white_F",
			"I_G_Quadbike_01_F",
			"I_MRAP_03_F",
			"I_Quadbike_01_F",
			"O_G_Quadbike_01_F",
			"O_MRAP_02_F",
			"O_Quadbike_01_F",
			"B_T_MRAP_01_F",
			"B_T_MRAP_01_gmg_F",
			"B_T_MRAP_01_hmg_F",
			"O_T_MRAP_02_ghex_F",
			"B_GEN_Offroad_01_gen_F",
			"C_Offroad_02_unarmed_black_F",
			"C_Offroad_02_unarmed_blue_F",
			"C_Offroad_02_unarmed_green_F",
			"C_Offroad_02_unarmed_orange_F",
			"C_Offroad_02_unarmed_red_F",
			"C_Offroad_02_unarmed_white_F",
			"I_C_Offroad_02_unarmed_F",
			"I_C_Offroad_02_unarmed_brown_F",
			"I_C_Offroad_02_unarmed_olive_F",
			"volha_Civ_01",
			"volha_Civ_02",
			"volha_Civ_03",
			"B_G_Van_01_fuel_F",
			"B_G_Van_01_transport_F",
			"B_Truck_01_Repair_F",
			"B_Truck_01_ammo_F",
			"B_Truck_01_box_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_transport_F",
			"C_IDAP_Truck_02_F",
			"C_IDAP_Truck_02_transport_F",
			"C_IDAP_Truck_02_water_F",
			"C_Truck_02_box_F",
			"C_Truck_02_covered_F",
			"C_Truck_02_fuel_F",
			"C_Truck_02_transport_F",
			"C_Van_01_box_F",
			"C_Van_01_box_red_F",
			"C_Van_01_box_white_F",
			"C_Van_01_fuel_F",
			"C_Van_01_fuel_red_F",
			"C_Van_01_fuel_red_v2_F",
			"C_Van_01_fuel_white_F",
			"C_Van_01_fuel_white_v2_F",
			"C_Van_01_transport_F",
			"C_Van_01_transport_red_F",
			"C_Van_01_transport_white_F",
			"I_G_Offroad_01_repair_F",
			"I_G_Van_01_fuel_F",
			"I_G_Van_01_transport_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_covered_F",
			"I_Truck_02_fuel_F",
			"I_Truck_02_medical_F",
			"I_Truck_02_transport_F",
			"O_G_Offroad_01_F",
			"O_G_Offroad_01_repair_F",
			"O_G_Van_01_fuel_F",
			"O_G_Van_01_transport_F",
			"O_Truck_02_Ammo_F",
			"O_Truck_02_box_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_fuel_F",
			"O_Truck_02_medical_F",
			"O_Truck_02_transport_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_device_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_transport_F",
			"I_G_Offroad_01_armed_F",	
			"B_APC_Wheeled_01_cannon_F",
			"B_G_Offroad_01_armed_F",
			"B_MRAP_01_gmg_F",
			"B_MRAP_01_hmg_F",
			"I_APC_Wheeled_03_cannon_F",
			"I_MRAP_03_gmg_F",
			"I_MRAP_03_hmg_F",
			"O_G_Offroad_01_armed_F",
			"O_MRAP_02_gmg_F",
			"O_MRAP_02_hmg_F",
			"O_T_MRAP_02_gmg_ghex_F",
			"HMMWV_M134",
			"HMMWV_M134_des",
			"BTR40_MG_TK_INS_EP1",
			"BTR40_MG_TK_GUE_EP1",
			"O_T_MRAP_02_hmg_ghex_F"
];

/**
 * List of class names of objects which can be towed.
 * Liste des noms de classes des objets remorquables.
 */
R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
			"B_G_Offroad_01_F",
			"B_G_Offroad_01_repair_F",
			"B_G_Quadbike_01_F",
			"B_MRAP_01_F",
			"B_Quadbike_01_F",
			"C_Hatchback_01_F",
			"C_Hatchback_01_beigecustom_F",
			"C_Hatchback_01_black_F",
			"C_Hatchback_01_blue_F",
			"C_Hatchback_01_bluecustom_F",
			"C_Hatchback_01_dark_F",
			"C_Hatchback_01_green_F",
			"C_Hatchback_01_grey_F",
			"C_Hatchback_01_sport_F",
			"C_Hatchback_01_sport_blue_F",
			"C_Hatchback_01_sport_green_F",
			"C_Hatchback_01_sport_grey_F",
			"C_Hatchback_01_sport_orange_F",
			"C_Hatchback_01_sport_red_F",
			"C_Hatchback_01_sport_white_F",
			"C_Hatchback_01_white_F",
			"C_Hatchback_01_yellow_F",
			"C_Kart_01_Blu_F",
			"C_Kart_01_F",
			"C_Kart_01_Fuel_F",
			"C_Kart_01_Red_F",
			"C_Kart_01_Vrana_F",
			"C_Kart_01_black_F",
			"C_Kart_01_green_F",
			"C_Kart_01_orange_F",
			"C_Kart_01_white_F",
			"C_Kart_01_yellow_F",
			"C_Offroad_01_F",
			"C_Offroad_01_blue_F",
			"C_Offroad_01_bluecustom_F",
			"C_Offroad_01_darkred_F",
			"C_Offroad_01_red_F",
			"C_Offroad_01_repair_F",
			"C_Offroad_01_sand_F",
			"C_Offroad_01_white_F",
			"C_Offroad_default_F",
			"C_Offroad_luxe_F",
			"C_Offroad_stripped_F",		
			"I_G_Offroad_01_F",
			"C_SUV_01_F",
			"C_IDAP_Offroad_01_F",
			"C_IDAP_Offroad_02_unarmed_F",
			"O_G_Offroad_01_F",
			"C_Quadbike_01_F",
			"C_Quadbike_01_black_F",
			"C_Quadbike_01_blue_F",
			"C_Quadbike_01_red_F",
			"C_Quadbike_01_white_F",
			"I_G_Quadbike_01_F",
			"I_MRAP_03_F",
			"I_Quadbike_01_F",
			"O_G_Quadbike_01_F",
			"O_MRAP_02_F",
			"O_Quadbike_01_F",
			"B_T_MRAP_01_F",
			"B_T_MRAP_01_gmg_F",
			"B_T_MRAP_01_hmg_F",
			"O_T_MRAP_02_ghex_F",
			"B_GEN_Offroad_01_gen_F",
			"C_Offroad_02_unarmed_black_F",
			"C_Offroad_02_unarmed_blue_F",
			"C_Offroad_02_unarmed_green_F",
			"C_Offroad_02_unarmed_orange_F",
			"C_Offroad_02_unarmed_red_F",
			"C_Offroad_02_unarmed_white_F",
			"I_C_Offroad_02_unarmed_F",
			"I_C_Offroad_02_unarmed_brown_F",
			"I_C_Offroad_02_unarmed_olive_F",
			"volha_Civ_01",
			"volha_Civ_02",
			"volha_Civ_03",
			"B_G_Van_01_fuel_F",
			"B_G_Van_01_transport_F",
			"B_Truck_01_Repair_F",
			"B_Truck_01_ammo_F",
			"B_Truck_01_box_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_transport_F",
			"C_IDAP_Truck_02_F",
			"C_IDAP_Truck_02_transport_F",
			"C_IDAP_Truck_02_water_F",
			"C_Truck_02_box_F",
			"C_Truck_02_covered_F",
			"C_Truck_02_fuel_F",
			"C_Truck_02_transport_F",
			"C_Van_01_box_F",
			"C_Van_01_box_red_F",
			"C_Van_01_box_white_F",
			"C_Van_01_fuel_F",
			"C_Van_01_fuel_red_F",
			"C_Van_01_fuel_red_v2_F",
			"C_Van_01_fuel_white_F",
			"C_Van_01_fuel_white_v2_F",
			"C_Van_01_transport_F",
			"C_Van_01_transport_red_F",
			"C_Van_01_transport_white_F",
			"I_G_Offroad_01_repair_F",
			"I_G_Van_01_fuel_F",
			"I_G_Van_01_transport_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_covered_F",
			"I_Truck_02_fuel_F",
			"I_Truck_02_medical_F",
			"I_Truck_02_transport_F",
			"O_G_Offroad_01_F",
			"O_G_Offroad_01_repair_F",
			"O_G_Van_01_fuel_F",
			"O_G_Van_01_transport_F",
			"O_Truck_02_Ammo_F",
			"O_Truck_02_box_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_fuel_F",
			"O_Truck_02_medical_F",
			"O_Truck_02_transport_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_device_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_transport_F",
			"I_G_Offroad_01_armed_F",	
			"B_APC_Wheeled_01_cannon_F",
			"B_G_Offroad_01_armed_F",
			"B_MRAP_01_gmg_F",
			"B_MRAP_01_hmg_F",
			"I_APC_Wheeled_03_cannon_F",
			"I_MRAP_03_gmg_F",
			"I_MRAP_03_hmg_F",
			"O_G_Offroad_01_armed_F",
			"O_MRAP_02_gmg_F",
			"O_MRAP_02_hmg_F",
			"O_T_MRAP_02_gmg_ghex_F",
			"HMMWV_M134",
			"HMMWV_M134_des",
			"BTR40_MG_TK_INS_EP1",
			"BTR40_MG_TK_GUE_EP1",
			"O_T_MRAP_02_hmg_ghex_F"
];


/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/

/**
 * List of class names of helicopters which can lift objects.
 * Liste des noms de classes des hélicoptères pouvant héliporter des objets.
 */
R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
			"B_Heli_Light_01_F",
			"B_Heli_Light_01_stripped_F",
			"B_Heli_Transport_03_unarmed_F",
			"B_Heli_Transport_03_unarmed_green_F",
			"C_Heli_Light_01_civil_F",
			"C_Heli_light_01_blueLine_F",
			"C_Heli_light_01_blue_F",
			"C_Heli_light_01_digital_F",
			"C_Heli_light_01_elliptical_F",
			"C_Heli_light_01_furious_F",
			"C_Heli_light_01_graywatcher_F",
			"C_Heli_light_01_ion_F",
			"C_Heli_light_01_jeans_F",
			"C_Heli_light_01_light_F",
			"C_Heli_light_01_luxe_F",
			"C_Heli_light_01_red_F",
			"C_Heli_light_01_shadow_F",
			"C_Heli_light_01_sheriff_F",
			"C_Heli_light_01_speedy_F",
			"C_Heli_light_01_stripped_F",
			"C_Heli_light_01_sunset_F",
			"C_Heli_light_01_vrana_F",
			"C_Heli_light_01_wasp_F",
			"C_Heli_light_01_wave_F",
			"I_Heli_light_03_unarmed_F",
			"O_Heli_Light_02_dynamicLoadout_F",			
			"O_Heli_Transport_04_F",
			"O_Heli_Transport_04_ammo_F",
			"O_Heli_Transport_04_ammo_black_F",
			"O_Heli_Transport_04_bench_F",
			"O_Heli_Transport_04_bench_black_F",
			"O_Heli_Transport_04_black_F",
			"O_Heli_Transport_04_box_F",
			"O_Heli_Transport_04_box_black_F",
			"O_Heli_Transport_04_covered_F",
			"O_Heli_Transport_04_covered_black_F",
			"O_Heli_Transport_04_fuel_F",
			"O_Heli_Transport_04_fuel_black_F",
			"O_Heli_Transport_04_medevac_F",
			"O_Heli_Transport_04_medevac_black_F",
			"O_Heli_Transport_04_repair_F",
			"O_Heli_Transport_04_repair_black_F",
			"B_Heli_Attack_01_F",							// disabled for newer version
			"B_Heli_Attack_01_dynamicLoadout_F",
			"B_Heli_Light_01_armed_F",					// disabled for newer version
			"B_Heli_Light_01_dynamicLoadout_F",
			"B_Heli_Transport_01_F",
			"B_Heli_Transport_01_camo_F",
			"B_Heli_Transport_03_F",
			"B_Heli_Transport_03_black_F",
			"I_Heli_Transport_02_F",
			"I_Heli_light_03_F",							// disabled for newer version
			"I_Heli_light_03_dynamicLoadout_F",
			"O_Heli_Attack_02_F",							// disabled for newer version
			"O_Heli_Attack_02_black_F",					// disabled for newer version
			"O_Heli_Attack_02_dynamicLoadout_F",
			"O_Heli_Attack_02_dynamicLoadout_black_F",
			"O_Heli_Light_02_F",
			"O_Heli_Light_02_unarmed_F",
			"O_Heli_Light_02_v2_F"
];

/**
 * List of class names of objects which can be lifted.
 * Liste des noms de classes des objets héliportables.
 */
R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
			"B_G_Offroad_01_F",
			"B_G_Offroad_01_repair_F",
			"B_G_Quadbike_01_F",
			"B_MRAP_01_F",
			"B_Quadbike_01_F",
			"C_Hatchback_01_F",
			"C_Hatchback_01_beigecustom_F",
			"C_Hatchback_01_black_F",
			"C_Hatchback_01_blue_F",
			"C_Hatchback_01_bluecustom_F",
			"C_Hatchback_01_dark_F",
			"C_Hatchback_01_green_F",
			"C_Hatchback_01_grey_F",
			"C_Hatchback_01_sport_F",
			"C_Hatchback_01_sport_blue_F",
			"C_Hatchback_01_sport_green_F",
			"C_Hatchback_01_sport_grey_F",
			"C_Hatchback_01_sport_orange_F",
			"C_Hatchback_01_sport_red_F",
			"C_Hatchback_01_sport_white_F",
			"C_Hatchback_01_white_F",
			"C_Hatchback_01_yellow_F",
			"C_Kart_01_Blu_F",
			"C_Kart_01_F",
			"C_Kart_01_Fuel_F",
			"C_Kart_01_Red_F",
			"C_Kart_01_Vrana_F",
			"C_Kart_01_black_F",
			"C_Kart_01_green_F",
			"C_Kart_01_orange_F",
			"C_Kart_01_white_F",
			"C_Kart_01_yellow_F",
			"C_Offroad_01_F",
			"C_Offroad_01_blue_F",
			"C_Offroad_01_bluecustom_F",
			"C_Offroad_01_darkred_F",
			"C_Offroad_01_red_F",
			"C_Offroad_01_repair_F",
			"C_Offroad_01_sand_F",
			"C_Offroad_01_white_F",
			"C_Offroad_default_F",
			"C_Offroad_luxe_F",
			"C_Offroad_stripped_F",		
			"I_G_Offroad_01_F",
			"C_SUV_01_F",
			"C_IDAP_Offroad_01_F",
			"C_IDAP_Offroad_02_unarmed_F",
			"O_G_Offroad_01_F",
			"C_Quadbike_01_F",
			"C_Quadbike_01_black_F",
			"C_Quadbike_01_blue_F",
			"C_Quadbike_01_red_F",
			"C_Quadbike_01_white_F",
			"I_G_Quadbike_01_F",
			"I_MRAP_03_F",
			"I_Quadbike_01_F",
			"O_G_Quadbike_01_F",
			"O_MRAP_02_F",
			"O_Quadbike_01_F",
			"B_T_MRAP_01_F",
			"B_T_MRAP_01_gmg_F",
			"B_T_MRAP_01_hmg_F",
			"O_T_MRAP_02_ghex_F",
			"B_GEN_Offroad_01_gen_F",
			"C_Offroad_02_unarmed_black_F",
			"C_Offroad_02_unarmed_blue_F",
			"C_Offroad_02_unarmed_green_F",
			"C_Offroad_02_unarmed_orange_F",
			"C_Offroad_02_unarmed_red_F",
			"C_Offroad_02_unarmed_white_F",
			"I_C_Offroad_02_unarmed_F",
			"I_C_Offroad_02_unarmed_brown_F",
			"I_C_Offroad_02_unarmed_olive_F",
			"volha_Civ_01",
			"volha_Civ_02",
			"volha_Civ_03",
			"B_G_Van_01_fuel_F",
			"B_G_Van_01_transport_F",
			"B_Truck_01_Repair_F",
			"B_Truck_01_ammo_F",
			"B_Truck_01_box_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_transport_F",
			"C_IDAP_Truck_02_F",
			"C_IDAP_Truck_02_transport_F",
			"C_IDAP_Truck_02_water_F",
			"C_Truck_02_box_F",
			"C_Truck_02_covered_F",
			"C_Truck_02_fuel_F",
			"C_Truck_02_transport_F",
			"C_Van_01_box_F",
			"C_Van_01_box_red_F",
			"C_Van_01_box_white_F",
			"C_Van_01_fuel_F",
			"C_Van_01_fuel_red_F",
			"C_Van_01_fuel_red_v2_F",
			"C_Van_01_fuel_white_F",
			"C_Van_01_fuel_white_v2_F",
			"C_Van_01_transport_F",
			"C_Van_01_transport_red_F",
			"C_Van_01_transport_white_F",
			"I_G_Offroad_01_repair_F",
			"I_G_Van_01_fuel_F",
			"I_G_Van_01_transport_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_covered_F",
			"I_Truck_02_fuel_F",
			"I_Truck_02_medical_F",
			"I_Truck_02_transport_F",
			"O_G_Offroad_01_F",
			"O_G_Offroad_01_repair_F",
			"O_G_Van_01_fuel_F",
			"O_G_Van_01_transport_F",
			"O_Truck_02_Ammo_F",
			"O_Truck_02_box_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_fuel_F",
			"O_Truck_02_medical_F",
			"O_Truck_02_transport_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_device_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_transport_F",
			"I_G_Offroad_01_armed_F",	
			"B_APC_Wheeled_01_cannon_F",
			"B_G_Offroad_01_armed_F",
			"B_MRAP_01_gmg_F",
			"B_MRAP_01_hmg_F",
			"I_APC_Wheeled_03_cannon_F",
			"I_MRAP_03_gmg_F",
			"I_MRAP_03_hmg_F",
			"O_G_Offroad_01_armed_F",
			"O_MRAP_02_gmg_F",
			"O_MRAP_02_hmg_F",
			"O_T_MRAP_02_gmg_ghex_F",
			"HMMWV_M134",
			"HMMWV_M134_des",
			"BTR40_MG_TK_INS_EP1",
			"BTR40_MG_TK_GUE_EP1",
			"O_T_MRAP_02_hmg_ghex_F",
			"B_Boat_Armed_01_minigun_F",
			"B_Boat_Transport_01_F",
			"B_G_Boat_Transport_01_F",
			"B_Lifeboat",
			"B_SDV_01_F",
			"C_Boat_Civil_01_F",
			"C_Boat_Civil_01_police_F",
			"C_Boat_Civil_01_rescue_F",
			"C_Rubberboat",
			"I_Boat_Armed_01_minigun_F",
			"I_Boat_Transport_01_F",
			"I_G_Boat_Transport_01_F",
			"I_SDV_01_F",
			"O_Boat_Transport_01_F",
			"O_G_Boat_Transport_01_F",
			"O_Lifeboat",
			"O_SDV_01_F"
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/

/*
 * This section uses a numeric quantification of capacity and cost of the objets.
 * For example, in a vehicle has a capacity of 100, we will be able to load in 5 objects costing 20 capacity units.
 * The capacity doesn't represent a real volume or weight, but a choice made for gameplay.
 *
 * Note : the priority of a declaration of cost/capacity to another one corresponds to the inverse order in the tables.
 *   It means that the most generic classes should be listed before the less generic classes.
 *   For example : the "Truck_F" class is a child of the "Car_F" class (see http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html).
 *   If "Car_F" is declared before "Truck_F" with a capacity of 40, and "Truck_F" is declared after with a capacity of 140,
 *   Then all the child classes of "Truck_F" will have a capacity of 140.
 *   And all the derived classes of "Car_F", not in "Truck_F", will have a capacity of 40.
 *
 *
 * Cette section utilise une quantification numérique de la capacité et du coût des objets.
 * Par exemple, dans un véhicule d'une capacité de 100, nous pouvons charger 5 objets coûtant 20 unités de capacité.
 * La capacité ne représente ni un poids, ni un volume, mais un choix fait pour la jouabilité.
 *
 * Note : la priorité d'une déclaration de coût/capacité sur une autre correspond à l'ordre inverse dans les tableaux.
 *   Cela implique que les classes les plus génériques doivent être listées avant les classes moins gnériques.
 *   Par exemple : la classe "Truck_F" est une classe dérviée de "Car_F" (voir http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html).
 *   Si "Car_F" est déclaré avant "Truck_F" avec une capacité de 40, et que "Truck_F" est déclaré après avec une capacité de 140,
 *   Alors toutes les classes dérivées de "Truck_F" auront une capacité de 140.
 *   Et toutes les classes dans "Car_F", non présentes dans "Truck_F", auront une capacité de 40.
 */

/**
 * List of class names of vehicles or cargo objects which can transport objects.
 * The second element of the nested arrays is the load capacity (in relation with the capacity cost of the objects).
 *
 * Liste des noms de classes des véhicules ou "objets contenant" pouvant transporter des objets.
 * Le deuxième élément des sous-tableaux est la capacité de chargement (en relation avec le coût de capacité des objets).
 */
R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	// e.g. : ["MyTransporterClassName1", itsCapacity], ["MyTransporterClassName2", itsCapacity]

		
			["B_G_Offroad_01_F", 60],
			["B_G_Offroad_01_repair_F", 60],
			["B_G_Quadbike_01_F", 60],
			["B_MRAP_01_F", 60],
			["B_Quadbike_01_F", 60],
			["C_Hatchback_01_F", 60],
			["C_Hatchback_01_beigecustom_F", 60],
			["C_Hatchback_01_black_F", 60],
			["C_Hatchback_01_blue_F", 60],
			["C_Hatchback_01_bluecustom_F", 60],
			["C_Hatchback_01_dark_F", 60],
			["C_Hatchback_01_green_F", 60],
			["C_Hatchback_01_grey_F", 60],
			["C_Hatchback_01_sport_F", 60],
			["C_Hatchback_01_sport_blue_F", 60],
			["C_Hatchback_01_sport_green_F", 60],
			["C_Hatchback_01_sport_grey_F", 60],
			["C_Hatchback_01_sport_orange_F", 60],
			["C_Hatchback_01_sport_red_F", 60],
			["C_Hatchback_01_sport_white_F", 60],
			["C_Hatchback_01_white_F", 60],
			["C_Hatchback_01_yellow_F", 60],
			["C_Kart_01_Blu_F", 60],
			["C_Kart_01_F", 60],
			["C_Kart_01_Fuel_F", 60],
			["C_Kart_01_Red_F", 60],
			["C_Kart_01_Vrana_F", 60],
			["C_Kart_01_black_F", 60],
			["C_Kart_01_green_F", 60],
			["C_Kart_01_orange_F", 60],
			["C_Kart_01_white_F", 60],
			["C_Kart_01_yellow_F", 60],
			["C_Offroad_01_F", 60],
			["C_Offroad_01_blue_F", 60],
			["C_Offroad_01_bluecustom_F", 60],
			["C_Offroad_01_darkred_F", 60],
			["C_Offroad_01_red_F", 60],
			["C_Offroad_01_repair_F", 60],
			["C_Offroad_01_sand_F", 60],
			["C_Offroad_01_white_F", 60],
			["C_Offroad_default_F", 60],
			["C_Offroad_luxe_F", 60],
			["C_Offroad_stripped_F", 60],		
			["I_G_Offroad_01_F", 60],
			["C_SUV_01_F", 60],
			["C_IDAP_Offroad_01_F", 60],
			["C_IDAP_Offroad_02_unarmed_F", 60],
			["O_G_Offroad_01_F", 60],
			["C_Quadbike_01_F", 60],
			["C_Quadbike_01_black_F", 60],
			["C_Quadbike_01_blue_F", 60],
			["C_Quadbike_01_red_F", 60],
			["C_Quadbike_01_white_F", 60],
			["I_G_Quadbike_01_F", 60],
			["I_MRAP_03_F", 60],
			["I_Quadbike_01_F", 60],
			["O_G_Quadbike_01_F", 60],
			["O_MRAP_02_F", 60],
			["O_Quadbike_01_F", 60],
			["B_T_MRAP_01_F", 60],
			["B_T_MRAP_01_gmg_F", 60],
			["B_T_MRAP_01_hmg_F", 60],
			["O_T_MRAP_02_ghex_F", 60],
			["B_GEN_Offroad_01_gen_F", 60],
			["C_Offroad_02_unarmed_black_F", 60],
			["C_Offroad_02_unarmed_blue_F", 60],
			["C_Offroad_02_unarmed_green_F", 60],
			["C_Offroad_02_unarmed_orange_F", 60],
			["C_Offroad_02_unarmed_red_F", 60],
			["C_Offroad_02_unarmed_white_F", 60],
			["I_C_Offroad_02_unarmed_F", 60],
			["I_C_Offroad_02_unarmed_brown_F", 60],
			["I_C_Offroad_02_unarmed_olive_F", 60],
			["volha_Civ_01", 60],
			["volha_Civ_02", 60],
			["volha_Civ_03", 60],
			["B_G_Van_01_fuel_F", 60],
			["B_G_Van_01_transport_F", 60],
			["B_Truck_01_Repair_F", 60],
			["B_Truck_01_ammo_F", 60],
			["B_Truck_01_box_F", 60],
			["B_Truck_01_covered_F", 60],
			["B_Truck_01_fuel_F", 60],
			["B_Truck_01_medical_F", 60],
			["B_Truck_01_mover_F", 60],
			["B_Truck_01_transport_F", 60],
			["C_IDAP_Truck_02_F", 60],
			["C_IDAP_Truck_02_transport_F", 60],
			["C_IDAP_Truck_02_water_F", 60],
			["C_Truck_02_box_F", 60],
			["C_Truck_02_covered_F", 60],
			["C_Truck_02_fuel_F", 60],
			["C_Truck_02_transport_F", 60],
			["C_Van_01_box_F", 60],
			["C_Van_01_box_red_F", 60],
			["C_Van_01_box_white_F", 60],
			["C_Van_01_fuel_F", 60],
			["C_Van_01_fuel_red_F", 60],
			["C_Van_01_fuel_red_v2_F", 60],
			["C_Van_01_fuel_white_F", 60],
			["C_Van_01_fuel_white_v2_F", 60],
			["C_Van_01_transport_F", 60],
			["C_Van_01_transport_red_F", 60],
			["C_Van_01_transport_white_F", 60],
			["I_G_Offroad_01_repair_F", 60],
			["I_G_Van_01_fuel_F", 60],
			["I_G_Van_01_transport_F", 60],
			["I_Truck_02_ammo_F", 60],
			["I_Truck_02_box_F", 60],
			["I_Truck_02_covered_F", 60],
			["I_Truck_02_fuel_F", 60],
			["I_Truck_02_medical_F", 60],
			["I_Truck_02_transport_F", 60],
			["O_G_Offroad_01_F", 60],
			["O_G_Offroad_01_repair_F", 60],
			["O_G_Van_01_fuel_F", 60],
			["O_G_Van_01_transport_F", 60],
			["O_Truck_02_Ammo_F", 60],
			["O_Truck_02_box_F", 60],
			["O_Truck_02_covered_F", 60],
			["O_Truck_02_fuel_F", 60],
			["O_Truck_02_medical_F", 60],
			["O_Truck_02_transport_F", 60],
			["O_Truck_03_ammo_F", 60],
			["O_Truck_03_covered_F", 60],
			["O_Truck_03_device_F", 60],
			["O_Truck_03_fuel_F", 60],
			["O_Truck_03_medical_F", 60],
			["O_Truck_03_repair_F", 60],
			["O_Truck_03_transport_F", 60],
			["I_G_Offroad_01_armed_F", 60],	
			["B_APC_Wheeled_01_cannon_F", 60],
			["B_G_Offroad_01_armed_F", 60],
			["B_MRAP_01_gmg_F", 60],
			["B_MRAP_01_hmg_F", 60],
			["I_APC_Wheeled_03_cannon_F", 60],
			["I_MRAP_03_gmg_F", 60],
			["I_MRAP_03_hmg_F", 60],
			["O_G_Offroad_01_armed_F", 60],
			["O_MRAP_02_gmg_F", 60],
			["O_MRAP_02_hmg_F", 60],
			["O_T_MRAP_02_gmg_ghex_F", 60],
			["HMMWV_M134", 60],
			["HMMWV_M134_des", 60],
			["BTR40_MG_TK_INS_EP1", 60],
			["BTR40_MG_TK_GUE_EP1", 60],
			["O_T_MRAP_02_hmg_ghex_F", 60],
			["B_Boat_Armed_01_minigun_F", 60],
			["B_Boat_Transport_01_F", 60],
			["B_G_Boat_Transport_01_F", 60],
			["B_Lifeboat", 60],
			["B_SDV_01_F", 60],
			["C_Boat_Civil_01_F", 60],
			["C_Boat_Civil_01_police_F", 60],
			["C_Boat_Civil_01_rescue_F", 60],
			["C_Rubberboat", 60],
			["I_Boat_Armed_01_minigun_F", 60],
			["I_Boat_Transport_01_F", 60],
			["I_G_Boat_Transport_01_F", 60],
			["I_SDV_01_F", 60],
			["O_Boat_Transport_01_F", 60],
			["O_G_Boat_Transport_01_F", 60],
			["O_Lifeboat", 60],
			["O_SDV_01_F", 60],
			["B_Heli_Light_01_F", 60],
			["B_Heli_Light_01_stripped_F", 60],
			["B_Heli_Transport_03_unarmed_F", 60],
			["B_Heli_Transport_03_unarmed_green_F", 60],
			["C_Heli_Light_01_civil_F", 60],
			["C_Heli_light_01_blueLine_F", 60],
			["C_Heli_light_01_blue_F", 60],
			["C_Heli_light_01_digital_F", 60],
			["C_Heli_light_01_elliptical_F", 60],
			["C_Heli_light_01_furious_F", 60],
			["C_Heli_light_01_graywatcher_F", 60],
			["C_Heli_light_01_ion_F", 60],
			["C_Heli_light_01_jeans_F", 60],
			["C_Heli_light_01_light_F", 60],
			["C_Heli_light_01_luxe_F", 60],
			["C_Heli_light_01_red_F", 60],
			["C_Heli_light_01_shadow_F", 60],
			["C_Heli_light_01_sheriff_F", 60],
			["C_Heli_light_01_speedy_F", 60],
			["C_Heli_light_01_stripped_F", 60],
			["C_Heli_light_01_sunset_F", 60],
			["C_Heli_light_01_vrana_F", 60],
			["C_Heli_light_01_wasp_F", 60],
			["C_Heli_light_01_wave_F", 60],
			["I_Heli_light_03_unarmed_F", 60],
			["O_Heli_Light_02_dynamicLoadout_F", 60],			
			["O_Heli_Transport_04_F", 60],
			["O_Heli_Transport_04_ammo_F", 60],
			["O_Heli_Transport_04_ammo_black_F", 60],
			["O_Heli_Transport_04_bench_F", 60],
			["O_Heli_Transport_04_bench_black_F", 60],
			["O_Heli_Transport_04_black_F", 60],
			["O_Heli_Transport_04_box_F", 60],
			["O_Heli_Transport_04_box_black_F", 60],
			["O_Heli_Transport_04_covered_F", 60],
			["O_Heli_Transport_04_covered_black_F", 60],
			["O_Heli_Transport_04_fuel_F", 60],
			["O_Heli_Transport_04_fuel_black_F", 60],
			["O_Heli_Transport_04_medevac_F", 60],
			["O_Heli_Transport_04_medevac_black_F", 60],
			["O_Heli_Transport_04_repair_F", 60],
			["O_Heli_Transport_04_repair_black_F", 60],
			["B_Heli_Attack_01_dynamicLoadout_F", 60],
			["B_Heli_Light_01_dynamicLoadout_F", 60],
			["B_Heli_Transport_01_F", 60],
			["B_Heli_Transport_01_camo_F", 60],
			["B_Heli_Transport_03_F", 60],
			["B_Heli_Transport_03_black_F", 60],
			["I_Heli_Transport_02_F", 60],
			["I_Heli_light_03_dynamicLoadout_F", 60],
			["O_Heli_Attack_02_dynamicLoadout_F", 60],
			["O_Heli_Attack_02_dynamicLoadout_black_F", 60],
			["O_Heli_Light_02_F", 60],
			["O_Heli_Light_02_unarmed_F", 60],
			["O_Heli_Light_02_v2_F", 60],
			["B_Plane_CAS_01_dynamicLoadout_F", 60],
			["GNT_C185", 60],
			["GNT_C185F", 60],
			["GNT_C185T", 60],
			["I_Plane_Fighter_03_AA_F", 60],
			["I_Plane_Fighter_03_CAS_F", 60],
			["I_Plane_Fighter_03_dynamicLoadout_F", 60],
			["O_Plane_CAS_02_dynamicLoadout_F", 60]


];

/**
 * List of class names of objects which can be loaded in transport vehicle/cargo.
 * The second element of the nested arrays is the cost capacity (in relation with the capacity of the vehicles).
 *
 * Liste des noms de classes des objets transportables.
 * Le deuxième élément des sous-tableaux est le coût de capacité (en relation avec la capacité des véhicules).
 */
R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	// e.g. : ["MyTransportableObjectClassName1", itsCost], ["MyTransportableObjectClassName2", itsCost]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

/**
 * List of class names of objects which can be carried and moved by a player.
 * Liste des noms de classes des objets qui peuvent être portés et déplacés par le joueur.
 */
R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	// e.g. : "MyMovableObjectClassName1", "MyMovableObjectClassName2"
];
