/**
 * English and French comments
 * Commentaires anglais et français
 *
 * This file is a template to add objetcs from an addon in the configuration variables of the logistics system.
 * Make a copy of this file and fill it. Then add a #include to this file in the file R3F_LOG\config.sqf.
 *
 * IMPORTANT NOTE : when a logistics feature is given to an object/vehicle class name, all the classes which inherit
 *                  of the parent/generic class (according to the CfgVehicles) will also have this feature.
 *                  CfgVehicles tree view example : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 *
 *
 * Ce fichier est un exemple vierge permettant d'ajouter des objets d'un addon dans la configuration du système de logistique.
 * Faites une copie de ce fichier et remplissez-le. Puis ajouter un #include vers celui-ci dans le fichier R3F_LOG\config.sqf.
 *
 * NOTE IMPORTANTE : lorsqu'une fonctionnalité logistique est accordée à un nom de classe d'objet/véhicule, les classes
 *                   héritant de cette classe mère/générique (selon le CfgVehicles) se verront également dotées de cette fonctionnalité.
 *                   Exemple d'arborescence du CfgVehicles : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 */

/**
 * List of class names of ground vehicles which can tow objects.
 * Liste des noms de classes des véhicules terrestres pouvant remorquer des objets.
 */
R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
	// e.g. : "MyTowingVehicleClassName1", "MyTowingVehicleClassName2"

  "CUP_C_UAZ_Open_TK_CIV",
  "CUP_C_UAZ_Unarmed_TK_CIV",
  "CUP_O_UAZ_AGS30_CHDKZ",
  "CUP_O_UAZ_AGS30_RU",
  "CUP_O_UAZ_AGS30_TKA",
  "CUP_O_UAZ_MG_CHDKZ",
  "CUP_O_UAZ_MG_RU",
  "CUP_O_UAZ_MG_TKA",
  "CUP_O_UAZ_Open_CHDKZ",
  "CUP_O_UAZ_Open_RU",
  "CUP_O_UAZ_Open_TKA",
  "CUP_O_UAZ_SPG9_CHDKZ",
  "CUP_O_UAZ_SPG9_RU",
  "CUP_O_UAZ_SPG9_TKA",
  "CUP_O_UAZ_Unarmed_CHDKZ",
  "CUP_O_UAZ_Unarmed_RU",
  "CUP_O_UAZ_Unarmed_TKA",
  "CUP_B_UAZ_AGS30_ACR",
  "CUP_B_UAZ_AGS30_CDF",
  "CUP_B_UAZ_MG_ACR",
  "CUP_B_UAZ_MG_CDF",
  "CUP_B_UAZ_Open_ACR",
  "CUP_B_UAZ_Open_CDF",
  "CUP_B_UAZ_SPG9_ACR",
  "CUP_B_UAZ_SPG9_CDF",
  "CUP_B_UAZ_Unarmed_ACR",
  "CUP_B_UAZ_Unarmed_CDF",
  "CUP_I_UAZ_AGS30_UN",
  "CUP_I_UAZ_MG_UN",
  "CUP_I_UAZ_Open_UN",
  "CUP_I_UAZ_SPG9_UN",
  "CUP_I_UAZ_Unarmed_UN",
  "CUP_B_Ural_CDF",
  "CUP_B_Ural_Empty_CDF",
  "CUP_B_Ural_Open_CDF",
  "CUP_B_Ural_Reammo_CDF",
  "CUP_B_Ural_Refuel_CDF",
  "CUP_B_Ural_Repair_CDF",
  "CUP_B_Ural_ZU23_CDF",
  "CUP_O_Ural_CHDKZ",
  "CUP_O_Ural_Empty_CHDKZ",
  "CUP_O_Ural_Empty_RU",
  "CUP_O_Ural_Empty_SLA",
  "CUP_O_Ural_Empty_TKA",
  "CUP_O_Ural_Open_CHDKZ",
  "CUP_O_Ural_Open_RU",
  "CUP_O_Ural_Open_SLA",
  "CUP_O_Ural_Open_TKA",
  "CUP_O_Ural_RU",
  "CUP_O_Ural_Reammo_CHDKZ",
  "CUP_O_Ural_Reammo_RU",
  "CUP_O_Ural_Reammo_SLA",
  "CUP_O_Ural_Reammo_TKA",
  "CUP_O_Ural_Refuel_CHDKZ",
  "CUP_O_Ural_Refuel_RU",
  "CUP_O_Ural_Refuel_SLA",
  "CUP_O_Ural_Refuel_TKA",
  "CUP_O_Ural_Repair_CHDKZ",
  "CUP_O_Ural_Repair_RU",
  "CUP_O_Ural_Repair_SLA",
  "CUP_O_Ural_Repair_TKA",
  "CUP_O_Ural_SLA",
  "CUP_O_Ural_TKA",
  "CUP_O_Ural_ZU23_CHDKZ",
  "CUP_O_Ural_ZU23_RU",
  "CUP_O_Ural_ZU23_SLA",
  "CUP_O_Ural_ZU23_TKA",
  "CUP_O_Ural_ZU23_TKM",
  "CUP_C_Ural_Civ_01",
  "CUP_C_Ural_Civ_02",
  "CUP_C_Ural_Civ_03",
  "CUP_C_Ural_Open_Civ_01",
  "CUP_C_Ural_Open_Civ_02",
  "CUP_C_Ural_Open_Civ_03",
  "CUP_I_Ural_Empty_UN",
  "CUP_I_Ural_Reammo_UN",
  "CUP_I_Ural_Repair_UN",
  "CUP_I_Ural_UN",
  "CUP_I_Ural_ZU23_NAPA",
  "CUP_I_Ural_ZU23_TK_Gue",
  "CUP_C_Datsun",
  "CUP_C_Datsun_4seat",
  "CUP_C_Datsun_Covered",
  "CUP_C_Datsun_Plain",
  "CUP_C_Datsun_Tubeframe",
  "CUP_I_Datsun_PK",
  "CUP_I_Datsun_PK_Random",
  "CUP_I_Datsun_PK_TK",
  "CUP_I_Datsun_PK_TK_Random",
  "CUP_O_Datsun_PK",
  "CUP_O_Datsun_PK_Random",
  "CUP_C_LR_Transport_CTK",
  "CUP_B_M1030",
  "CUP_BAF_Jackal2_GMG_D",
  "CUP_BAF_Jackal2_GMG_W",
  "CUP_BAF_Jackal2_L2A1_D",
  "CUP_BAF_Jackal2_L2A1_W",
  "CUP_B_Dingo_Des",
  "CUP_B_Dingo_GL_Des",
  "CUP_B_Dingo_GL_Wdl",
  "CUP_B_Dingo_Wdl",
  "CUP_B_HMMWV_AGS_GPK_ACR",
  "CUP_B_HMMWV_Ambulance_ACR",
  "CUP_B_HMMWV_Ambulance_USA",
  "CUP_B_HMMWV_Ambulance_USMC",
  "CUP_B_HMMWV_Avenger_USA",
  "CUP_B_HMMWV_Avenger_USMC",
  "CUP_B_HMMWV_Crows_M2_USA",
  "CUP_B_HMMWV_Crows_MK19_USA",
  "CUP_B_HMMWV_DSHKM_GPK_ACR",
  "CUP_B_HMMWV_M1114_USMC",
  "CUP_B_HMMWV_M2_GPK_ACR",
  "CUP_B_HMMWV_M2_GPK_USA",
  "CUP_B_HMMWV_M2_USA",
  "CUP_B_HMMWV_M2_USMC",
  "CUP_B_HMMWV_MK19_USA",
  "CUP_B_HMMWV_MK19_USMC",
  "CUP_B_HMMWV_SOV_USA",
  "CUP_B_HMMWV_TOW_USA",
  "CUP_B_HMMWV_TOW_USMC",
  "CUP_B_HMMWV_Terminal_USA",
  "CUP_B_HMMWV_Transport_USA",
  "CUP_B_HMMWV_Unarmed_USA",
  "CUP_B_HMMWV_Unarmed_USMC",
  "CUP_B_LR_Ambulance_CZ_D",
  "CUP_B_LR_Ambulance_CZ_W",
  "CUP_B_LR_Ambulance_GB_D",
  "CUP_B_LR_Ambulance_GB_W",
  "CUP_B_LR_MG_CZ_W",
  "CUP_B_LR_MG_GB_W",
  "CUP_B_LR_Special_CZ_W",
  "CUP_B_LR_Special_Des_CZ_D",
  "CUP_B_LR_Transport_CZ_D",
  "CUP_B_LR_Transport_CZ_W",
  "CUP_B_LR_Transport_GB_D",
  "CUP_B_LR_Transport_GB_W",
  "CUP_O_LR_Ambulance_TKA",
  "CUP_O_LR_MG_TKA",
  "CUP_O_LR_MG_TKM",
  "CUP_O_LR_SPG9_TKA",
  "CUP_O_LR_SPG9_TKM",
  "CUP_O_LR_Transport_TKA",
  "CUP_O_LR_Transport_TKM",
  "CUP_I_LR_Transport_RACS",
  "CUP_I_LR_MG_RACS",
  "CUP_I_LR_Ambulance_RACS",
  "CUP_I_BRDM2_ATGM_NAPA",
  "CUP_I_BRDM2_ATGM_TK_Gue",
  "CUP_I_BRDM2_HQ_NAPA",
  "CUP_I_BRDM2_HQ_TK_Gue",
  "CUP_I_BRDM2_HQ_UN",
  "CUP_I_BRDM2_NAPA",
  "CUP_I_BRDM2_TK_Gue",
  "CUP_I_BRDM2_UN",
  "CUP_O_BRDM2_ATGM_CHDKZ",
  "CUP_O_BRDM2_ATGM_SLA",
  "CUP_O_BRDM2_ATGM_TKA",
  "CUP_O_BRDM2_CHDKZ",
  "CUP_O_BRDM2_HQ_CHDKZ",
  "CUP_O_BRDM2_HQ_SLA",
  "CUP_O_BRDM2_HQ_TKA",
  "CUP_O_BRDM2_SLA",
  "CUP_O_BRDM2_TKA",
  "CUP_B_BRDM2_ATGM_CDF",
  "CUP_B_BRDM2_CDF",
  "CUP_B_BRDM2_HQ_CDF",
  "CUP_B_LAV25M240_USMC",
  "CUP_B_LAV25_HQ_USMC",
  "CUP_B_LAV25_USMC",
  "CUP_B_BM21_CDF",
  "CUP_O_BM21_CHDKZ",
  "CUP_O_BM21_RU",
  "CUP_O_BM21_SLA",
  "CUP_O_BM21_TKA",
  "CUP_O_BTR60_TK",
  "CUP_O_BTR90_HQ_RU",
  "CUP_O_BTR90_RU",
  "CUP_C_Octavia_CIV",
  "CUP_C_Skoda_Red_Civ",
  "CUP_C_Skoda_White_Civ",
  "CUP_C_Skoda_Blue_Civ",
  "CUP_C_Skoda_Green_Civ",
  "CUP_C_Golf4_red_Civ",
  "CUP_C_Golf4_black_Civ",
  "CUP_C_Golf4_yellow_Civ",
  "CUP_C_Golf4_blue_Civ",
  "CUP_C_Golf4_white_Civ",
  "CUP_C_Golf4_green_Civ",
  "CUP_C_Golf4_random_Civ",
  "CUP_C_Golf4_whiteblood_Civ",
  "CUP_C_Golf4_camo_Civ",
  "CUP_C_Golf4_camodigital_Civ",
  "CUP_C_Golf4_camodark_Civ",
  "CUP_C_Golf4_reptile_Civ",
  "CUP_C_Golf4_kitty_Civ",
  "CUP_B_M1126_ICV_M2_Desert",
  "CUP_B_M1126_ICV_M2_Desert_Slat",
  "CUP_B_M1126_ICV_M2_Woodland",
  "CUP_B_M1126_ICV_M2_Woodland_Slat",
  "CUP_B_M1126_ICV_Mk19_Desert",
  "CUP_B_M1126_ICV_Mk19_Desert_Slat",
  "CUP_B_M1126_ICV_Mk19_Woodland",
  "CUP_B_M1126_ICV_Mk19_Woodland_Slat",
  "CUP_B_M1128_MGS_Desert",
  "CUP_B_M1128_MGS_Desert_Slat",
  "CUP_B_M1128_MGS_Woodland",
  "CUP_B_M1128_MGS_Woodland_Slat",
  "CUP_B_M1129_MC_MK19_Desert",
  "CUP_B_M1129_MC_MK19_Desert_Slat",
  "CUP_B_M1129_MC_MK19_Woodland",
  "CUP_B_M1129_MC_MK19_Woodland_Slat",
  "CUP_B_M1130_CV_M2_Desert",
  "CUP_B_M1130_CV_M2_Desert_Slat",
  "CUP_B_M1130_CV_M2_Woodland",
  "CUP_B_M1130_CV_M2_Woodland_Slat",
  "CUP_B_M1133_MEV_Desert",
  "CUP_B_M1133_MEV_Desert_Slat",
  "CUP_B_M1133_MEV_Woodland",
  "CUP_B_M1133_MEV_Woodland_Slat",
  "CUP_B_M1135_ATGMV_Desert",
  "CUP_B_M1135_ATGMV_Desert_Slat",
  "CUP_B_M1135_ATGMV_Woodland",
  "CUP_B_M1135_ATGMV_Woodland_Slat",
  "CUP_B_TowingTractor_USMC",
  "CUP_B_AAV_USMC",
  "CUP_B_M113_Med_USA",
  "CUP_B_M113_USA",
  "CUP_I_M113_Med_RACS",
  "CUP_I_M113_Med_UN",
  "CUP_I_M113_RACS",
  "CUP_I_M113_UN",
  "CUP_O_M113_Med_TKA",
  "CUP_O_M113_TKA",
  "CUP_B_M163_USA",
  "CUP_I_M163_RACS",
  "CUP_B_M1A1_DES_USMC",
  "CUP_B_M1A1_DES_US_Army",
  "CUP_B_M1A1_Woodland_USMC",
  "CUP_B_M1A1_Woodland_US_Army",
  "CUP_B_M1A2_TUSK_MG_DES_USMC",
  "CUP_B_M1A2_TUSK_MG_DES_US_Army",
  "CUP_B_M1A2_TUSK_MG_USMC",
  "CUP_B_M1A2_TUSK_MG_US_Army",
  "CUP_B_M270_DPICM_USA",
  "CUP_B_M270_DPICM_USMC",
  "CUP_B_M270_HE_USA",
  "CUP_B_M270_HE_USMC",
  "CUP_B_M2Bradley_USA_D",
  "CUP_B_M2Bradley_USA_W",
  "CUP_B_M2A3Bradley_USA_D",
  "CUP_B_M2A3Bradley_USA_W",
  "CUP_I_T55_TK_GUE",
  "CUP_O_T55_TK",
  "CUP_O_T72_CHDKZ",
  "CUP_O_T72_RU",
  "CUP_O_T72_SLA",
  "CUP_O_T72_TKA",
  "CUP_B_T72_CDF",
  "CUP_I_T72_NAPA",
  "CUP_I_T72_RACS",
  "CUP_B_ZSU23_CDF",
  "CUP_O_ZSU23_ChDKZ",
  "CUP_O_ZSU23_SLA",
  "CUP_O_ZSU23_TK",
  "CUP_T34_BASE",
  "CUP_I_T34_NAPA",
  "CUP_I_T34_TK_GUE",
  "CUP_O_T34_TKA",
  "CUP_B_FV432_Bulldog_GB_W_RWS",
  "CUP_B_Dingo_GER_Wdl",
  "CUP_B_Mastiff_HMG_GB_W",
  "CUP_B_Ridgback_HMG_GB_W",
  "CUP_I_SUV_Armored_ION",
  "CUP_I_BTR40_TKG",
  "CUP_O_GAZ_Vodnik_PK_RU",
  "CUP_B_BAF_Coyote_L2A1_W",
  "CUP_B_BAF_Coyote_L2A1_D"




];

/**
 * List of class names of objects which can be towed.
 * Liste des noms de classes des objets remorquables.
 */
R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
	// e.g. : "MyTowableObjectClassName1", "MyTowableObjectClassName2"

  "CUP_C_UAZ_Open_TK_CIV",
  "CUP_C_UAZ_Unarmed_TK_CIV",
  "CUP_O_UAZ_AGS30_CHDKZ",
  "CUP_O_UAZ_AGS30_RU",
  "CUP_O_UAZ_AGS30_TKA",
  "CUP_O_UAZ_MG_CHDKZ",
  "CUP_O_UAZ_MG_RU",
  "CUP_O_UAZ_MG_TKA",
  "CUP_O_UAZ_Open_CHDKZ",
  "CUP_O_UAZ_Open_RU",
  "CUP_O_UAZ_Open_TKA",
  "CUP_O_UAZ_SPG9_CHDKZ",
  "CUP_O_UAZ_SPG9_RU",
  "CUP_O_UAZ_SPG9_TKA",
  "CUP_O_UAZ_Unarmed_CHDKZ",
  "CUP_O_UAZ_Unarmed_RU",
  "CUP_O_UAZ_Unarmed_TKA",
  "CUP_B_UAZ_AGS30_ACR",
  "CUP_B_UAZ_AGS30_CDF",
  "CUP_B_UAZ_MG_ACR",
  "CUP_B_UAZ_MG_CDF",
  "CUP_B_UAZ_Open_ACR",
  "CUP_B_UAZ_Open_CDF",
  "CUP_B_UAZ_SPG9_ACR",
  "CUP_B_UAZ_SPG9_CDF",
  "CUP_B_UAZ_Unarmed_ACR",
  "CUP_B_UAZ_Unarmed_CDF",
  "CUP_I_UAZ_AGS30_UN",
  "CUP_I_UAZ_MG_UN",
  "CUP_I_UAZ_Open_UN",
  "CUP_I_UAZ_SPG9_UN",
  "CUP_I_UAZ_Unarmed_UN",
  "CUP_B_Ural_CDF",
  "CUP_B_Ural_Empty_CDF",
  "CUP_B_Ural_Open_CDF",
  "CUP_B_Ural_Reammo_CDF",
  "CUP_B_Ural_Refuel_CDF",
  "CUP_B_Ural_Repair_CDF",
  "CUP_B_Ural_ZU23_CDF",
  "CUP_O_Ural_CHDKZ",
  "CUP_O_Ural_Empty_CHDKZ",
  "CUP_O_Ural_Empty_RU",
  "CUP_O_Ural_Empty_SLA",
  "CUP_O_Ural_Empty_TKA",
  "CUP_O_Ural_Open_CHDKZ",
  "CUP_O_Ural_Open_RU",
  "CUP_O_Ural_Open_SLA",
  "CUP_O_Ural_Open_TKA",
  "CUP_O_Ural_RU",
  "CUP_O_Ural_Reammo_CHDKZ",
  "CUP_O_Ural_Reammo_RU",
  "CUP_O_Ural_Reammo_SLA",
  "CUP_O_Ural_Reammo_TKA",
  "CUP_O_Ural_Refuel_CHDKZ",
  "CUP_O_Ural_Refuel_RU",
  "CUP_O_Ural_Refuel_SLA",
  "CUP_O_Ural_Refuel_TKA",
  "CUP_O_Ural_Repair_CHDKZ",
  "CUP_O_Ural_Repair_RU",
  "CUP_O_Ural_Repair_SLA",
  "CUP_O_Ural_Repair_TKA",
  "CUP_O_Ural_SLA",
  "CUP_O_Ural_TKA",
  "CUP_O_Ural_ZU23_CHDKZ",
  "CUP_O_Ural_ZU23_RU",
  "CUP_O_Ural_ZU23_SLA",
  "CUP_O_Ural_ZU23_TKA",
  "CUP_O_Ural_ZU23_TKM",
  "CUP_C_Ural_Civ_01",
  "CUP_C_Ural_Civ_02",
  "CUP_C_Ural_Civ_03",
  "CUP_C_Ural_Open_Civ_01",
  "CUP_C_Ural_Open_Civ_02",
  "CUP_C_Ural_Open_Civ_03",
  "CUP_I_Ural_Empty_UN",
  "CUP_I_Ural_Reammo_UN",
  "CUP_I_Ural_Repair_UN",
  "CUP_I_Ural_UN",
  "CUP_I_Ural_ZU23_NAPA",
  "CUP_I_Ural_ZU23_TK_Gue",
  "CUP_C_Datsun",
  "CUP_C_Datsun_4seat",
  "CUP_C_Datsun_Covered",
  "CUP_C_Datsun_Plain",
  "CUP_C_Datsun_Tubeframe",
  "CUP_I_Datsun_PK",
  "CUP_I_Datsun_PK_Random",
  "CUP_I_Datsun_PK_TK",
  "CUP_I_Datsun_PK_TK_Random",
  "CUP_O_Datsun_PK",
  "CUP_O_Datsun_PK_Random",
  "CUP_C_LR_Transport_CTK",
  "CUP_B_M1030",
  "CUP_BAF_Jackal2_GMG_D",
  "CUP_BAF_Jackal2_GMG_W",
  "CUP_BAF_Jackal2_L2A1_D",
  "CUP_BAF_Jackal2_L2A1_W",
  "CUP_B_Dingo_Des",
  "CUP_B_Dingo_GL_Des",
  "CUP_B_Dingo_GL_Wdl",
  "CUP_B_Dingo_Wdl",
  "CUP_B_HMMWV_AGS_GPK_ACR",
  "CUP_B_HMMWV_Ambulance_ACR",
  "CUP_B_HMMWV_Ambulance_USA",
  "CUP_B_HMMWV_Ambulance_USMC",
  "CUP_B_HMMWV_Avenger_USA",
  "CUP_B_HMMWV_Avenger_USMC",
  "CUP_B_HMMWV_Crows_M2_USA",
  "CUP_B_HMMWV_Crows_MK19_USA",
  "CUP_B_HMMWV_DSHKM_GPK_ACR",
  "CUP_B_HMMWV_M1114_USMC",
  "CUP_B_HMMWV_M2_GPK_ACR",
  "CUP_B_HMMWV_M2_GPK_USA",
  "CUP_B_HMMWV_M2_USA",
  "CUP_B_HMMWV_M2_USMC",
  "CUP_B_HMMWV_MK19_USA",
  "CUP_B_HMMWV_MK19_USMC",
  "CUP_B_HMMWV_SOV_USA",
  "CUP_B_HMMWV_TOW_USA",
  "CUP_B_HMMWV_TOW_USMC",
  "CUP_B_HMMWV_Terminal_USA",
  "CUP_B_HMMWV_Transport_USA",
  "CUP_B_HMMWV_Unarmed_USA",
  "CUP_B_HMMWV_Unarmed_USMC",
  "CUP_B_LR_Ambulance_CZ_D",
  "CUP_B_LR_Ambulance_CZ_W",
  "CUP_B_LR_Ambulance_GB_D",
  "CUP_B_LR_Ambulance_GB_W",
  "CUP_B_LR_MG_CZ_W",
  "CUP_B_LR_MG_GB_W",
  "CUP_B_LR_Special_CZ_W",
  "CUP_B_LR_Special_Des_CZ_D",
  "CUP_B_LR_Transport_CZ_D",
  "CUP_B_LR_Transport_CZ_W",
  "CUP_B_LR_Transport_GB_D",
  "CUP_B_LR_Transport_GB_W",
  "CUP_O_LR_Ambulance_TKA",
  "CUP_O_LR_MG_TKA",
  "CUP_O_LR_MG_TKM",
  "CUP_O_LR_SPG9_TKA",
  "CUP_O_LR_SPG9_TKM",
  "CUP_O_LR_Transport_TKA",
  "CUP_O_LR_Transport_TKM",
  "CUP_I_LR_Transport_RACS",
  "CUP_I_LR_MG_RACS",
  "CUP_I_LR_Ambulance_RACS",
  "CUP_I_BRDM2_ATGM_NAPA",
  "CUP_I_BRDM2_ATGM_TK_Gue",
  "CUP_I_BRDM2_HQ_NAPA",
  "CUP_I_BRDM2_HQ_TK_Gue",
  "CUP_I_BRDM2_HQ_UN",
  "CUP_I_BRDM2_NAPA",
  "CUP_I_BRDM2_TK_Gue",
  "CUP_I_BRDM2_UN",
  "CUP_O_BRDM2_ATGM_CHDKZ",
  "CUP_O_BRDM2_ATGM_SLA",
  "CUP_O_BRDM2_ATGM_TKA",
  "CUP_O_BRDM2_CHDKZ",
  "CUP_O_BRDM2_HQ_CHDKZ",
  "CUP_O_BRDM2_HQ_SLA",
  "CUP_O_BRDM2_HQ_TKA",
  "CUP_O_BRDM2_SLA",
  "CUP_O_BRDM2_TKA",
  "CUP_B_BRDM2_ATGM_CDF",
  "CUP_B_BRDM2_CDF",
  "CUP_B_BRDM2_HQ_CDF",
  "CUP_B_LAV25M240_USMC",
  "CUP_B_LAV25_HQ_USMC",
  "CUP_B_LAV25_USMC",
  "CUP_B_BM21_CDF",
  "CUP_O_BM21_CHDKZ",
  "CUP_O_BM21_RU",
  "CUP_O_BM21_SLA",
  "CUP_O_BM21_TKA",
  "CUP_O_BTR60_TK",
  "CUP_O_BTR90_HQ_RU",
  "CUP_O_BTR90_RU",
  "CUP_C_Octavia_CIV",
  "CUP_C_Skoda_Red_Civ",
  "CUP_C_Skoda_White_Civ",
  "CUP_C_Skoda_Blue_Civ",
  "CUP_C_Skoda_Green_Civ",
  "CUP_C_Golf4_red_Civ",
  "CUP_C_Golf4_black_Civ",
  "CUP_C_Golf4_yellow_Civ",
  "CUP_C_Golf4_blue_Civ",
  "CUP_C_Golf4_white_Civ",
  "CUP_C_Golf4_green_Civ",
  "CUP_C_Golf4_random_Civ",
  "CUP_C_Golf4_whiteblood_Civ",
  "CUP_C_Golf4_camo_Civ",
  "CUP_C_Golf4_camodigital_Civ",
  "CUP_C_Golf4_camodark_Civ",
  "CUP_C_Golf4_reptile_Civ",
  "CUP_C_Golf4_kitty_Civ",
  "CUP_B_M1126_ICV_M2_Desert",
  "CUP_B_M1126_ICV_M2_Desert_Slat",
  "CUP_B_M1126_ICV_M2_Woodland",
  "CUP_B_M1126_ICV_M2_Woodland_Slat",
  "CUP_B_M1126_ICV_Mk19_Desert",
  "CUP_B_M1126_ICV_Mk19_Desert_Slat",
  "CUP_B_M1126_ICV_Mk19_Woodland",
  "CUP_B_M1126_ICV_Mk19_Woodland_Slat",
  "CUP_B_M1128_MGS_Desert",
  "CUP_B_M1128_MGS_Desert_Slat",
  "CUP_B_M1128_MGS_Woodland",
  "CUP_B_M1128_MGS_Woodland_Slat",
  "CUP_B_M1129_MC_MK19_Desert",
  "CUP_B_M1129_MC_MK19_Desert_Slat",
  "CUP_B_M1129_MC_MK19_Woodland",
  "CUP_B_M1129_MC_MK19_Woodland_Slat",
  "CUP_B_M1130_CV_M2_Desert",
  "CUP_B_M1130_CV_M2_Desert_Slat",
  "CUP_B_M1130_CV_M2_Woodland",
  "CUP_B_M1130_CV_M2_Woodland_Slat",
  "CUP_B_M1133_MEV_Desert",
  "CUP_B_M1133_MEV_Desert_Slat",
  "CUP_B_M1133_MEV_Woodland",
  "CUP_B_M1133_MEV_Woodland_Slat",
  "CUP_B_M1135_ATGMV_Desert",
  "CUP_B_M1135_ATGMV_Desert_Slat",
  "CUP_B_M1135_ATGMV_Woodland",
  "CUP_B_M1135_ATGMV_Woodland_Slat",
  "CUP_B_TowingTractor_USMC",
  "CUP_B_AAV_USMC",
  "CUP_B_M113_Med_USA",
  "CUP_B_M113_USA",
  "CUP_I_M113_Med_RACS",
  "CUP_I_M113_Med_UN",
  "CUP_I_M113_RACS",
  "CUP_I_M113_UN",
  "CUP_O_M113_Med_TKA",
  "CUP_O_M113_TKA",
  "CUP_B_M163_USA",
  "CUP_I_M163_RACS",
  "CUP_B_M1A1_DES_USMC",
  "CUP_B_M1A1_DES_US_Army",
  "CUP_B_M1A1_Woodland_USMC",
  "CUP_B_M1A1_Woodland_US_Army",
  "CUP_B_M1A2_TUSK_MG_DES_USMC",
  "CUP_B_M1A2_TUSK_MG_DES_US_Army",
  "CUP_B_M1A2_TUSK_MG_USMC",
  "CUP_B_M1A2_TUSK_MG_US_Army",
  "CUP_B_M270_DPICM_USA",
  "CUP_B_M270_DPICM_USMC",
  "CUP_B_M270_HE_USA",
  "CUP_B_M270_HE_USMC",
  "CUP_B_M2Bradley_USA_D",
  "CUP_B_M2Bradley_USA_W",
  "CUP_B_M2A3Bradley_USA_D",
  "CUP_B_M2A3Bradley_USA_W",
  "CUP_I_T55_TK_GUE",
  "CUP_O_T55_TK",
  "CUP_O_T72_CHDKZ",
  "CUP_O_T72_RU",
  "CUP_O_T72_SLA",
  "CUP_O_T72_TKA",
  "CUP_B_T72_CDF",
  "CUP_I_T72_NAPA",
  "CUP_I_T72_RACS",
  "CUP_B_ZSU23_CDF",
  "CUP_O_ZSU23_ChDKZ",
  "CUP_O_ZSU23_SLA",
  "CUP_O_ZSU23_TK",
  "CUP_T34_BASE",
  "CUP_I_T34_NAPA",
  "CUP_I_T34_TK_GUE",
  "CUP_O_T34_TKA",
  "CUP_B_FV432_Bulldog_GB_W_RWS",
  "CUP_B_Dingo_GER_Wdl",
  "CUP_B_Mastiff_HMG_GB_W",
  "CUP_B_Ridgback_HMG_GB_W",
  "CUP_I_SUV_Armored_ION",
  "CUP_I_BTR40_TKG",
  "CUP_O_GAZ_Vodnik_PK_RU",
  "CUP_B_BAF_Coyote_L2A1_W",
  "CUP_B_BAF_Coyote_L2A1_D"
];


/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/

/**
 * List of class names of helicopters which can lift objects.
 * Liste des noms de classes des hélicoptères pouvant héliporter des objets.
 */
R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
	// e.g. : "MyLifterVehicleClassName1", "MyLifterVehicleClassName2"

  "CUP_B_AH1Z",
  "CUP_B_AH1Z_14RndHydrax",
  "CUP_B_AH1Z_7RndHydra",
  "CUP_B_AH1Z_AT",
  "CUP_B_AH1Z_Escort",
  "CUP_B_AH1Z_NOAA",
  "CUP_B_AH1Z_NoWeapons",
  "CUP_B_AH1_AT_BAF",
  "CUP_B_AH1_BAF",
  "CUP_B_AH1_ES_BAF",
  "CUP_B_AH1_MR_BAF",
  "CUP_B_AH1_NO_BAF",
  "CUP_B_AH64D_AT_USA",
  "CUP_B_AH64D_ES_USA",
  "CUP_B_AH64D_MR_USA",
  "CUP_B_AH64D_NO_USA",
  "CUP_B_AH64D_USA",
  "CUP_B_AW159_Armed_BAF",
  "CUP_B_AW159_Unarmed_BAF",
  "CUP_B_CH47F_GB",
  "CUP_B_CH47F_USA",
  "CUP_B_CH53E_USMC",
  "CUP_B_MH60S_FFV_USMC",
  "CUP_B_MH60S_USMC",
  "CUP_B_UH1Y_GUNSHIP_USMC",
  "CUP_B_UH1Y_MEV_USMC",
  "CUP_B_UH1Y_UNA_USMC",
  "CUP_B_UH60L_FFV_US",
  "CUP_B_UH60L_US",
  "CUP_B_UH60L_Unarmed_FFV_MEV_US",
  "CUP_B_UH60L_Unarmed_FFV_US",
  "CUP_B_UH60L_Unarmed_US",
  "CUP_I_UH60L_FFV_RACS",
  "CUP_I_UH60L_RACS",
  "CUP_I_UH60L_Unarmed_FFV_MEV_Racs",
  "CUP_I_UH60L_Unarmed_FFV_Racs",
  "CUP_I_UH60L_Unarmed_RACS",
  "CUP_B_UH60M_FFV_US",
  "CUP_B_UH60M_US",
  "CUP_B_UH60M_Unarmed_FFV_MEV_US",
  "CUP_B_UH60M_Unarmed_FFV_US",
  "CUP_B_UH60M_Unarmed_US",
  "CUP_O_Mi8_CHDKZ",
  "CUP_O_Mi8_RU",
  "CUP_O_Mi8_SLA_1",
  "CUP_O_Mi8_SLA_2",
  "CUP_O_Mi8_medevac_CHDKZ",
  "CUP_O_Mi8_medevac_RU",
  "CUP_B_Mi171Sh_ACR",
  "CUP_B_Mi171Sh_Unarmed_ACR",
  "CUP_B_Mi17_CDF",
  "CUP_B_Mi17_medevac_CDF",
  "CUP_I_Mi17_UN",
  "CUP_O_Mi17_TK",
  "CUP_C_Mi17_Civilian_RU",
  "CUP_B_Mi24_D_CDF",
  "CUP_I_Mi24_D_ION",
  "CUP_I_Mi24_D_UN",
  "CUP_O_Mi24_D_TK",
  "CUP_O_Mi24_P_RU",
  "CUP_O_Mi24_V_RU",
  "CUP_B_Mi35_CZ",
  "CUP_O_UH1H_TKA",
  "CUP_I_UH1H_TK_GUE",
  "CUP_B_UH1D_GER_KSK",
  "CUP_B_UH1D_GER_KSK_DES",
  "CUP_B_Merlin_HC3_GB",
  "CUP_B_Merlin_HC3A_GB",
  "CUP_B_AW159_Unarmed_GB",
  "CUP_B_AW159_Hellfire_GB",
  "CUP_B_AW159_Cannon_GB",
  "CUP_B_SA330_Puma_HC1_BAF",
  "CUP_B_SA330_Puma_HC2_BAF",
  "CUP_I_SA330_Puma_HC1_RACS",
  "CUP_I_SA330_Puma_HC2_RACS",
  "CUP_O_KA50_SLA",
  "CUP_O_KA50_AA_SLA",
  "CUP_O_KA50_RU",
  "CUP_O_KA50_AA_RU",
  "CUP_B_MI6A_CDF",
  "CUP_B_AH6J_ESCORT_USA",
  "CUP_B_MH6J_USA",
  "CUP_B_AH1Z_NoWeapons",
  "CUP_O_UH1H_SLA",
  "CUP_O_UH1H_TKA"
  
];

/**
 * List of class names of objects which can be lifted.
 * Liste des noms de classes des objets héliportables.
 */
R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	// e.g. : "MyLiftableObjectClassName1", "MyLiftableObjectClassName2"

  "CUP_C_UAZ_Open_TK_CIV",
  "CUP_C_UAZ_Unarmed_TK_CIV",
  "CUP_O_UAZ_AGS30_CHDKZ",
  "CUP_O_UAZ_AGS30_RU",
  "CUP_O_UAZ_AGS30_TKA",
  "CUP_O_UAZ_MG_CHDKZ",
  "CUP_O_UAZ_MG_RU",
  "CUP_O_UAZ_MG_TKA",
  "CUP_O_UAZ_Open_CHDKZ",
  "CUP_O_UAZ_Open_RU",
  "CUP_O_UAZ_Open_TKA",
  "CUP_O_UAZ_SPG9_CHDKZ",
  "CUP_O_UAZ_SPG9_RU",
  "CUP_O_UAZ_SPG9_TKA",
  "CUP_O_UAZ_Unarmed_CHDKZ",
  "CUP_O_UAZ_Unarmed_RU",
  "CUP_O_UAZ_Unarmed_TKA",
  "CUP_B_UAZ_AGS30_ACR",
  "CUP_B_UAZ_AGS30_CDF",
  "CUP_B_UAZ_MG_ACR",
  "CUP_B_UAZ_MG_CDF",
  "CUP_B_UAZ_Open_ACR",
  "CUP_B_UAZ_Open_CDF",
  "CUP_B_UAZ_SPG9_ACR",
  "CUP_B_UAZ_SPG9_CDF",
  "CUP_B_UAZ_Unarmed_ACR",
  "CUP_B_UAZ_Unarmed_CDF",
  "CUP_I_UAZ_AGS30_UN",
  "CUP_I_UAZ_MG_UN",
  "CUP_I_UAZ_Open_UN",
  "CUP_I_UAZ_SPG9_UN",
  "CUP_I_UAZ_Unarmed_UN",
  "CUP_B_Ural_CDF",
  "CUP_B_Ural_Empty_CDF",
  "CUP_B_Ural_Open_CDF",
  "CUP_B_Ural_Reammo_CDF",
  "CUP_B_Ural_Refuel_CDF",
  "CUP_B_Ural_Repair_CDF",
  "CUP_B_Ural_ZU23_CDF",
  "CUP_O_Ural_CHDKZ",
  "CUP_O_Ural_Empty_CHDKZ",
  "CUP_O_Ural_Empty_RU",
  "CUP_O_Ural_Empty_SLA",
  "CUP_O_Ural_Empty_TKA",
  "CUP_O_Ural_Open_CHDKZ",
  "CUP_O_Ural_Open_RU",
  "CUP_O_Ural_Open_SLA",
  "CUP_O_Ural_Open_TKA",
  "CUP_O_Ural_RU",
  "CUP_O_Ural_Reammo_CHDKZ",
  "CUP_O_Ural_Reammo_RU",
  "CUP_O_Ural_Reammo_SLA",
  "CUP_O_Ural_Reammo_TKA",
  "CUP_O_Ural_Refuel_CHDKZ",
  "CUP_O_Ural_Refuel_RU",
  "CUP_O_Ural_Refuel_SLA",
  "CUP_O_Ural_Refuel_TKA",
  "CUP_O_Ural_Repair_CHDKZ",
  "CUP_O_Ural_Repair_RU",
  "CUP_O_Ural_Repair_SLA",
  "CUP_O_Ural_Repair_TKA",
  "CUP_O_Ural_SLA",
  "CUP_O_Ural_TKA",
  "CUP_O_Ural_ZU23_CHDKZ",
  "CUP_O_Ural_ZU23_RU",
  "CUP_O_Ural_ZU23_SLA",
  "CUP_O_Ural_ZU23_TKA",
  "CUP_O_Ural_ZU23_TKM",
  "CUP_C_Ural_Civ_01",
  "CUP_C_Ural_Civ_02",
  "CUP_C_Ural_Civ_03",
  "CUP_C_Ural_Open_Civ_01",
  "CUP_C_Ural_Open_Civ_02",
  "CUP_C_Ural_Open_Civ_03",
  "CUP_I_Ural_Empty_UN",
  "CUP_I_Ural_Reammo_UN",
  "CUP_I_Ural_Repair_UN",
  "CUP_I_Ural_UN",
  "CUP_I_Ural_ZU23_NAPA",
  "CUP_I_Ural_ZU23_TK_Gue",
  "CUP_C_Datsun",
  "CUP_C_Datsun_4seat",
  "CUP_C_Datsun_Covered",
  "CUP_C_Datsun_Plain",
  "CUP_C_Datsun_Tubeframe",
  "CUP_I_Datsun_PK",
  "CUP_I_Datsun_PK_Random",
  "CUP_I_Datsun_PK_TK",
  "CUP_I_Datsun_PK_TK_Random",
  "CUP_O_Datsun_PK",
  "CUP_O_Datsun_PK_Random",
  "CUP_C_LR_Transport_CTK",
  "CUP_B_M1030",
  "CUP_BAF_Jackal2_GMG_D",
  "CUP_BAF_Jackal2_GMG_W",
  "CUP_BAF_Jackal2_L2A1_D",
  "CUP_BAF_Jackal2_L2A1_W",
  "CUP_B_Dingo_Des",
  "CUP_B_Dingo_GL_Des",
  "CUP_B_Dingo_GL_Wdl",
  "CUP_B_Dingo_Wdl",
  "CUP_B_HMMWV_AGS_GPK_ACR",
  "CUP_B_HMMWV_Ambulance_ACR",
  "CUP_B_HMMWV_Ambulance_USA",
  "CUP_B_HMMWV_Ambulance_USMC",
  "CUP_B_HMMWV_Avenger_USA",
  "CUP_B_HMMWV_Avenger_USMC",
  "CUP_B_HMMWV_Crows_M2_USA",
  "CUP_B_HMMWV_Crows_MK19_USA",
  "CUP_B_HMMWV_DSHKM_GPK_ACR",
  "CUP_B_HMMWV_M1114_USMC",
  "CUP_B_HMMWV_M2_GPK_ACR",
  "CUP_B_HMMWV_M2_GPK_USA",
  "CUP_B_HMMWV_M2_USA",
  "CUP_B_HMMWV_M2_USMC",
  "CUP_B_HMMWV_MK19_USA",
  "CUP_B_HMMWV_MK19_USMC",
  "CUP_B_HMMWV_SOV_USA",
  "CUP_B_HMMWV_TOW_USA",
  "CUP_B_HMMWV_TOW_USMC",
  "CUP_B_HMMWV_Terminal_USA",
  "CUP_B_HMMWV_Transport_USA",
  "CUP_B_HMMWV_Unarmed_USA",
  "CUP_B_HMMWV_Unarmed_USMC",
  "CUP_B_LR_Ambulance_CZ_D",
  "CUP_B_LR_Ambulance_CZ_W",
  "CUP_B_LR_Ambulance_GB_D",
  "CUP_B_LR_Ambulance_GB_W",
  "CUP_B_LR_MG_CZ_W",
  "CUP_B_LR_MG_GB_W",
  "CUP_B_LR_Special_CZ_W",
  "CUP_B_LR_Special_Des_CZ_D",
  "CUP_B_LR_Transport_CZ_D",
  "CUP_B_LR_Transport_CZ_W",
  "CUP_B_LR_Transport_GB_D",
  "CUP_B_LR_Transport_GB_W",
  "CUP_O_LR_Ambulance_TKA",
  "CUP_O_LR_MG_TKA",
  "CUP_O_LR_MG_TKM",
  "CUP_O_LR_SPG9_TKA",
  "CUP_O_LR_SPG9_TKM",
  "CUP_O_LR_Transport_TKA",
  "CUP_O_LR_Transport_TKM",
  "CUP_I_LR_Transport_RACS",
  "CUP_I_LR_MG_RACS",
  "CUP_I_LR_Ambulance_RACS",
  "CUP_I_BRDM2_ATGM_NAPA",
  "CUP_I_BRDM2_ATGM_TK_Gue",
  "CUP_I_BRDM2_HQ_NAPA",
  "CUP_I_BRDM2_HQ_TK_Gue",
  "CUP_I_BRDM2_HQ_UN",
  "CUP_I_BRDM2_NAPA",
  "CUP_I_BRDM2_TK_Gue",
  "CUP_I_BRDM2_UN",
  "CUP_O_BRDM2_ATGM_CHDKZ",
  "CUP_O_BRDM2_ATGM_SLA",
  "CUP_O_BRDM2_ATGM_TKA",
  "CUP_O_BRDM2_CHDKZ",
  "CUP_O_BRDM2_HQ_CHDKZ",
  "CUP_O_BRDM2_HQ_SLA",
  "CUP_O_BRDM2_HQ_TKA",
  "CUP_O_BRDM2_SLA",
  "CUP_O_BRDM2_TKA",
  "CUP_B_BRDM2_ATGM_CDF",
  "CUP_B_BRDM2_CDF",
  "CUP_B_BRDM2_HQ_CDF",
  "CUP_B_LAV25M240_USMC",
  "CUP_B_LAV25_HQ_USMC",
  "CUP_B_LAV25_USMC",
  "CUP_B_BM21_CDF",
  "CUP_O_BM21_CHDKZ",
  "CUP_O_BM21_RU",
  "CUP_O_BM21_SLA",
  "CUP_O_BM21_TKA",
  "CUP_O_BTR60_TK",
  "CUP_O_BTR90_HQ_RU",
  "CUP_O_BTR90_RU",
  "CUP_C_Octavia_CIV",
  "CUP_C_Skoda_Red_Civ",
  "CUP_C_Skoda_White_Civ",
  "CUP_C_Skoda_Blue_Civ",
  "CUP_C_Skoda_Green_Civ",
  "CUP_C_Golf4_red_Civ",
  "CUP_C_Golf4_black_Civ",
  "CUP_C_Golf4_yellow_Civ",
  "CUP_C_Golf4_blue_Civ",
  "CUP_C_Golf4_white_Civ",
  "CUP_C_Golf4_green_Civ",
  "CUP_C_Golf4_random_Civ",
  "CUP_C_Golf4_whiteblood_Civ",
  "CUP_C_Golf4_camo_Civ",
  "CUP_C_Golf4_camodigital_Civ",
  "CUP_C_Golf4_camodark_Civ",
  "CUP_C_Golf4_reptile_Civ",
  "CUP_C_Golf4_kitty_Civ",
  "CUP_B_M1126_ICV_M2_Desert",
  "CUP_B_M1126_ICV_M2_Desert_Slat",
  "CUP_B_M1126_ICV_M2_Woodland",
  "CUP_B_M1126_ICV_M2_Woodland_Slat",
  "CUP_B_M1126_ICV_Mk19_Desert",
  "CUP_B_M1126_ICV_Mk19_Desert_Slat",
  "CUP_B_M1126_ICV_Mk19_Woodland",
  "CUP_B_M1126_ICV_Mk19_Woodland_Slat",
  "CUP_B_M1128_MGS_Desert",
  "CUP_B_M1128_MGS_Desert_Slat",
  "CUP_B_M1128_MGS_Woodland",
  "CUP_B_M1128_MGS_Woodland_Slat",
  "CUP_B_M1129_MC_MK19_Desert",
  "CUP_B_M1129_MC_MK19_Desert_Slat",
  "CUP_B_M1129_MC_MK19_Woodland",
  "CUP_B_M1129_MC_MK19_Woodland_Slat",
  "CUP_B_M1130_CV_M2_Desert",
  "CUP_B_M1130_CV_M2_Desert_Slat",
  "CUP_B_M1130_CV_M2_Woodland",
  "CUP_B_M1130_CV_M2_Woodland_Slat",
  "CUP_B_M1133_MEV_Desert",
  "CUP_B_M1133_MEV_Desert_Slat",
  "CUP_B_M1133_MEV_Woodland",
  "CUP_B_M1133_MEV_Woodland_Slat",
  "CUP_B_M1135_ATGMV_Desert",
  "CUP_B_M1135_ATGMV_Desert_Slat",
  "CUP_B_M1135_ATGMV_Woodland",
  "CUP_B_M1135_ATGMV_Woodland_Slat",
  "CUP_B_TowingTractor_USMC",
  "CUP_B_AAV_USMC",
  "CUP_B_M113_Med_USA",
  "CUP_B_M113_USA",
  "CUP_I_M113_Med_RACS",
  "CUP_I_M113_Med_UN",
  "CUP_I_M113_RACS",
  "CUP_I_M113_UN",
  "CUP_O_M113_Med_TKA",
  "CUP_O_M113_TKA",
  "CUP_B_M163_USA",
  "CUP_I_M163_RACS",
  "CUP_B_M1A1_DES_USMC",
  "CUP_B_M1A1_DES_US_Army",
  "CUP_B_M1A1_Woodland_USMC",
  "CUP_B_M1A1_Woodland_US_Army",
  "CUP_B_M1A2_TUSK_MG_DES_USMC",
  "CUP_B_M1A2_TUSK_MG_DES_US_Army",
  "CUP_B_M1A2_TUSK_MG_USMC",
  "CUP_B_M1A2_TUSK_MG_US_Army",
  "CUP_B_M270_DPICM_USA",
  "CUP_B_M270_DPICM_USMC",
  "CUP_B_M270_HE_USA",
  "CUP_B_M270_HE_USMC",
  "CUP_B_M2Bradley_USA_D",
  "CUP_B_M2Bradley_USA_W",
  "CUP_B_M2A3Bradley_USA_D",
  "CUP_B_M2A3Bradley_USA_W",
  "CUP_I_T55_TK_GUE",
  "CUP_O_T55_TK",
  "CUP_O_T72_CHDKZ",
  "CUP_O_T72_RU",
  "CUP_O_T72_SLA",
  "CUP_O_T72_TKA",
  "CUP_B_T72_CDF",
  "CUP_I_T72_NAPA",
  "CUP_I_T72_RACS",
  "CUP_B_ZSU23_CDF",
  "CUP_O_ZSU23_ChDKZ",
  "CUP_O_ZSU23_SLA",
  "CUP_O_ZSU23_TK",
  "CUP_T34_BASE",
  "CUP_I_T34_NAPA",
  "CUP_I_T34_TK_GUE",
  "CUP_O_T34_TKA",
  "CUP_B_FV432_Bulldog_GB_W_RWS",
  "CUP_B_Dingo_GER_Wdl",
  "CUP_B_Mastiff_HMG_GB_W",
  "CUP_B_Ridgback_HMG_GB_W",
  "CUP_I_SUV_Armored_ION",
  "CUP_I_BTR40_TKG",
  "CUP_O_GAZ_Vodnik_PK_RU",
  "CUP_B_BAF_Coyote_L2A1_W",
  "CUP_B_BAF_Coyote_L2A1_D"
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/

/*
 * This section uses a numeric quantification of capacity and cost of the objets.
 * For example, in a vehicle has a capacity of 100, we will be able to load in 5 objects costing 20 capacity units.
 * The capacity doesn't represent a real volume or weight, but a choice made for gameplay.
 *
 * Note : the priority of a declaration of cost/capacity to another one corresponds to the inverse order in the tables.
 *   It means that the most generic classes should be listed before the less generic classes.
 *   For example : the "Truck_F" class is a child of the "Car_F" class (see http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html).
 *   If "Car_F" is declared before "Truck_F" with a capacity of 40, and "Truck_F" is declared after with a capacity of 140,
 *   Then all the child classes of "Truck_F" will have a capacity of 140.
 *   And all the derived classes of "Car_F", not in "Truck_F", will have a capacity of 40.
 *
 *
 * Cette section utilise une quantification numérique de la capacité et du coût des objets.
 * Par exemple, dans un véhicule d'une capacité de 100, nous pouvons charger 5 objets coûtant 20 unités de capacité.
 * La capacité ne représente ni un poids, ni un volume, mais un choix fait pour la jouabilité.
 *
 * Note : la priorité d'une déclaration de coût/capacité sur une autre correspond à l'ordre inverse dans les tableaux.
 *   Cela implique que les classes les plus génériques doivent être listées avant les classes moins gnériques.
 *   Par exemple : la classe "Truck_F" est une classe dérviée de "Car_F" (voir http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html).
 *   Si "Car_F" est déclaré avant "Truck_F" avec une capacité de 40, et que "Truck_F" est déclaré après avec une capacité de 140,
 *   Alors toutes les classes dérivées de "Truck_F" auront une capacité de 140.
 *   Et toutes les classes dans "Car_F", non présentes dans "Truck_F", auront une capacité de 40.
 */

/**
 * List of class names of vehicles or cargo objects which can transport objects.
 * The second element of the nested arrays is the load capacity (in relation with the capacity cost of the objects).
 *
 * Liste des noms de classes des véhicules ou "objets contenant" pouvant transporter des objets.
 * Le deuxième élément des sous-tableaux est la capacité de chargement (en relation avec le coût de capacité des objets).
 */
R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	// e.g. : ["MyTransporterClassName1", itsCapacity], ["MyTransporterClassName2", itsCapacity]

  ["CUP_B_AH1Z", 70],
  ["CUP_B_AH1Z_7RndHydra", 70],
  ["CUP_B_AH1Z_AT", 70],
  ["CUP_B_AH1Z_Escort", 70],
  ["CUP_B_AH1Z_NOAA", 70],
  ["CUP_B_AH1Z_NoWeapons", 70],
  ["CUP_B_AH1_AT_BAF", 70],
  ["CUP_B_AH1_BAF", 70],
  ["CUP_B_AH1_ES_BAF", 70],
  ["CUP_B_AH1_MR_BAF", 70],
  ["CUP_B_AH1_NO_BAF", 70],
  ["CUP_B_AH64D_AT_USA", 70],
  ["CUP_B_AH64D_ES_USA", 70],
  ["CUP_B_AH64D_MR_USA", 70],
  ["CUP_B_AH64D_NO_USA", 70],
  ["CUP_B_AH64D_USA", 70],
  ["CUP_B_AW159_Armed_BAF", 70],
  ["CUP_B_AW159_Unarmed_BAF", 70],
  ["CUP_B_CH47F_GB", 70],
  ["CUP_B_CH47F_USA", 70],
  ["CUP_B_CH53E_USMC", 70],
  ["CUP_B_MH60S_FFV_USMC", 70],
  ["CUP_B_MH60S_USMC", 70],
  ["CUP_B_UH1Y_GUNSHIP_USMC", 70],
  ["CUP_B_UH1Y_MEV_USMC", 70],
  ["CUP_B_UH1Y_UNA_USMC", 70],
  ["CUP_B_UH60L_FFV_US", 70],
  ["CUP_B_UH60L_US", 70],
  ["CUP_B_UH60L_Unarmed_FFV_MEV_US", 70],
  ["CUP_B_UH60L_Unarmed_FFV_US", 70],
  ["CUP_B_UH60L_Unarmed_US", 70],
  ["CUP_I_UH60L_FFV_RACS", 70],
  ["CUP_I_UH60L_RACS", 70],
  ["CUP_I_UH60L_Unarmed_FFV_MEV_Racs", 70],
  ["CUP_I_UH60L_Unarmed_FFV_Racs", 70],
  ["CUP_I_UH60L_Unarmed_RACS", 70],
  ["CUP_B_UH60M_FFV_US", 70],
  ["CUP_B_UH60M_US", 70],
  ["CUP_B_UH60M_Unarmed_FFV_MEV_US", 70],
  ["CUP_B_UH60M_Unarmed_FFV_US", 70],
  ["CUP_B_UH60M_Unarmed_US", 70],
  ["CUP_O_Mi8_CHDKZ", 70],
  ["CUP_O_Mi8_RU", 70],
  ["CUP_O_Mi8_SLA_1", 70],
  ["CUP_O_Mi8_SLA_2", 70],
  ["CUP_O_Mi8_medevac_CHDKZ", 70],
  ["CUP_O_Mi8_medevac_RU", 70],
  ["CUP_B_Mi171Sh_ACR", 70],
  ["CUP_B_Mi171Sh_Unarmed_ACR", 70],
  ["CUP_B_Mi17_CDF", 70],
  ["CUP_B_Mi17_medevac_CDF", 70],
  ["CUP_I_Mi17_UN", 70],
  ["CUP_O_Mi17_TK", 70],
  ["CUP_C_Mi17_Civilian_RU", 70],
  ["CUP_B_Mi24_D_CDF", 70],
  ["CUP_I_Mi24_D_ION", 70],
  ["CUP_I_Mi24_D_UN", 70],
  ["CUP_O_Mi24_D_TK", 70],
  ["CUP_O_Mi24_P_RU", 70],
  ["CUP_O_Mi24_V_RU", 70],
  ["CUP_B_Mi35_CZ", 70],
  ["CUP_O_UH1H_TKA", 70],
  ["CUP_I_UH1H_TK_GUE", 70],
  ["CUP_B_UH1D_GER_KSK", 70],
  ["CUP_B_UH1D_GER_KSK_DES", 70],
  ["CUP_B_Merlin_HC3_GB", 70],
  ["CUP_B_Merlin_HC3A_GB", 70],
  ["CUP_B_AW159_Unarmed_GB", 70],
  ["CUP_B_AW159_Hellfire_GB", 70],
  ["CUP_B_AW159_Cannon_GB", 70],
  ["CUP_B_SA330_Puma_HC1_BAF", 70],
  ["CUP_B_SA330_Puma_HC2_BAF", 70],
  ["CUP_I_SA330_Puma_HC1_RACS", 70],
  ["CUP_I_SA330_Puma_HC2_RACS", 70],
  ["CUP_O_KA50_SLA", 70],
  ["CUP_O_KA50_AA_SLA", 70],
  ["CUP_O_KA50_RU", 70],
  ["CUP_O_KA50_AA_RU", 70],
  ["CUP_C_UAZ_Open_TK_CIV", 60],
  ["CUP_C_UAZ_Unarmed_TK_CIV", 60],
  ["CUP_O_UAZ_AGS30_CHDKZ", 60],
  ["CUP_O_UAZ_AGS30_RU", 60],
  ["CUP_O_UAZ_AGS30_TKA", 60],
  ["CUP_O_UAZ_MG_CHDKZ", 60],
  ["CUP_O_UAZ_MG_RU", 60],
  ["CUP_O_UAZ_MG_TKA", 60],
  ["CUP_O_UAZ_Open_CHDKZ", 60],
  ["CUP_O_UAZ_Open_RU", 60],
  ["CUP_O_UAZ_Open_TKA", 60],
  ["CUP_O_UAZ_SPG9_CHDKZ", 60],
  ["CUP_O_UAZ_SPG9_RU", 60],
  ["CUP_O_UAZ_SPG9_TKA", 60],
  ["CUP_O_UAZ_Unarmed_CHDKZ", 60],
  ["CUP_O_UAZ_Unarmed_RU", 60],
  ["CUP_O_UAZ_Unarmed_TKA", 60],
  ["CUP_B_UAZ_AGS30_ACR", 60],
  ["CUP_B_UAZ_AGS30_CDF", 60],
  ["CUP_B_UAZ_MG_ACR", 60],
  ["CUP_B_UAZ_MG_CDF", 60],
  ["CUP_B_UAZ_Open_ACR", 60],
  ["CUP_B_UAZ_Open_CDF", 60],
  ["CUP_B_UAZ_SPG9_ACR", 60],
  ["CUP_B_UAZ_SPG9_CDF", 60],
  ["CUP_B_UAZ_Unarmed_ACR", 60],
  ["CUP_B_UAZ_Unarmed_CDF", 60],
  ["CUP_I_UAZ_AGS30_UN", 60],
  ["CUP_I_UAZ_MG_UN", 60],
  ["CUP_I_UAZ_Open_UN", 60],
  ["CUP_I_UAZ_SPG9_UN", 60],
  ["CUP_I_UAZ_Unarmed_UN", 60],
  ["CUP_B_Ural_CDF", 120],
  ["CUP_B_Ural_Empty_CDF", 120],
  ["CUP_B_Ural_Open_CDF", 120],
  ["CUP_B_Ural_Reammo_CDF", 120],
  ["CUP_B_Ural_Refuel_CDF", 120],
  ["CUP_B_Ural_Repair_CDF", 120],
  ["CUP_B_Ural_ZU23_CDF", 120],
  ["CUP_O_Ural_CHDKZ", 120],
  ["CUP_O_Ural_Empty_CHDKZ", 120],
  ["CUP_O_Ural_Empty_RU", 120],
  ["CUP_O_Ural_Empty_SLA", 120],
  ["CUP_O_Ural_Empty_TKA", 120],
  ["CUP_O_Ural_Open_CHDKZ", 120],
  ["CUP_O_Ural_Open_RU", 120],
  ["CUP_O_Ural_Open_SLA", 120],
  ["CUP_O_Ural_Open_TKA", 120],
  ["CUP_O_Ural_RU", 120],
  ["CUP_O_Ural_Reammo_CHDKZ", 120],
  ["CUP_O_Ural_Reammo_RU", 120],
  ["CUP_O_Ural_Reammo_SLA", 120],
  ["CUP_O_Ural_Reammo_TKA", 120],
  ["CUP_O_Ural_Refuel_CHDKZ", 120],
  ["CUP_O_Ural_Refuel_RU", 120],
  ["CUP_O_Ural_Refuel_SLA", 120],
  ["CUP_O_Ural_Refuel_TKA", 120],
  ["CUP_O_Ural_Repair_CHDKZ", 120],
  ["CUP_O_Ural_Repair_RU", 120],
  ["CUP_O_Ural_Repair_SLA", 120],
  ["CUP_O_Ural_Repair_TKA", 120],
  ["CUP_O_Ural_SLA", 120],
  ["CUP_O_Ural_TKA", 120],
  ["CUP_O_Ural_ZU23_CHDKZ", 120],
  ["CUP_O_Ural_ZU23_RU", 120],
  ["CUP_O_Ural_ZU23_SLA", 120],
  ["CUP_O_Ural_ZU23_TKA", 120],
  ["CUP_O_Ural_ZU23_TKM", 120],
  ["CUP_C_Ural_Civ_01", 120],
  ["CUP_C_Ural_Civ_02", 120],
  ["CUP_C_Ural_Civ_03", 120],
  ["CUP_C_Ural_Open_Civ_01", 120],
  ["CUP_C_Ural_Open_Civ_02", 120],
  ["CUP_C_Ural_Open_Civ_03", 120],
  ["CUP_I_Ural_Empty_UN", 120],
  ["CUP_I_Ural_Reammo_UN", 120],
  ["CUP_I_Ural_Repair_UN", 120],
  ["CUP_I_Ural_UN", 120],
  ["CUP_I_Ural_ZU23_NAPA", 120],
  ["CUP_I_Ural_ZU23_TK_Gue", 120],
  ["CUP_C_Datsun", 60],
  ["CUP_C_Datsun_4seat", 60],
  ["CUP_C_Datsun_Covered", 60],
  ["CUP_C_Datsun_Plain", 60],
  ["CUP_C_Datsun_Tubeframe", 60],
  ["CUP_I_Datsun_PK", 60],
  ["CUP_I_Datsun_PK_Random", 60],
  ["CUP_I_Datsun_PK_TK", 60],
  ["CUP_I_Datsun_PK_TK_Random", 60],
  ["CUP_O_Datsun_PK", 60],
  ["CUP_O_Datsun_PK_Random", 60],
  ["CUP_C_LR_Transport_CTK", 60],
  ["CUP_B_M1030", 30],
  ["CUP_BAF_Jackal2_GMG_D", 90],
  ["CUP_BAF_Jackal2_GMG_W", 90],
  ["CUP_BAF_Jackal2_L2A1_D", 90],
  ["CUP_BAF_Jackal2_L2A1_W", 90],
  ["CUP_B_Dingo_Des", 90],
  ["CUP_B_Dingo_GL_Des", 90],
  ["CUP_B_Dingo_GL_Wdl", 90],
  ["CUP_B_Dingo_Wdl", 90],
  ["CUP_B_HMMWV_AGS_GPK_ACR", 60],
  ["CUP_B_HMMWV_Ambulance_ACR", 60],
  ["CUP_B_HMMWV_Ambulance_USA", 60],
  ["CUP_B_HMMWV_Ambulance_USMC", 60],
  ["CUP_B_HMMWV_Avenger_USA", 60],
  ["CUP_B_HMMWV_Avenger_USMC", 60],
  ["CUP_B_HMMWV_Crows_M2_USA", 60],
  ["CUP_B_HMMWV_Crows_MK19_USA", 60],
  ["CUP_B_HMMWV_DSHKM_GPK_ACR", 60],
  ["CUP_B_HMMWV_M1114_USMC", 60],
  ["CUP_B_HMMWV_M2_GPK_ACR", 60],
  ["CUP_B_HMMWV_M2_GPK_USA", 60],
  ["CUP_B_HMMWV_M2_USA", 60],
  ["CUP_B_HMMWV_M2_USMC", 60],
  ["CUP_B_HMMWV_MK19_USA", 60],
  ["CUP_B_HMMWV_MK19_USMC", 60],
  ["CUP_B_HMMWV_SOV_USA", 60],
  ["CUP_B_HMMWV_TOW_USA", 60],
  ["CUP_B_HMMWV_TOW_USMC", 60],
  ["CUP_B_HMMWV_Terminal_USA", 60],
  ["CUP_B_HMMWV_Transport_USA", 60],
  ["CUP_B_HMMWV_Unarmed_USA", 60],
  ["CUP_B_HMMWV_Unarmed_USMC", 60],
  ["CUP_B_LR_Ambulance_CZ_D", 60],
  ["CUP_B_LR_Ambulance_CZ_W", 60],
  ["CUP_B_LR_Ambulance_GB_D", 60],
  ["CUP_B_LR_Ambulance_GB_W", 60],
  ["CUP_B_LR_MG_CZ_W", 60],
  ["CUP_B_LR_MG_GB_W", 60],
  ["CUP_B_LR_Special_CZ_W", 60],
  ["CUP_B_LR_Special_Des_CZ_D", 60],
  ["CUP_B_LR_Transport_CZ_D", 60],
  ["CUP_B_LR_Transport_CZ_W", 60],
  ["CUP_B_LR_Transport_GB_D", 60],
  ["CUP_B_LR_Transport_GB_W", 60],
  ["CUP_O_LR_Ambulance_TKA", 60],
  ["CUP_O_LR_MG_TKA", 60],
  ["CUP_O_LR_MG_TKM", 60],
  ["CUP_O_LR_SPG9_TKA", 60],
  ["CUP_O_LR_SPG9_TKM", 60],
  ["CUP_O_LR_Transport_TKA", 60],
  ["CUP_O_LR_Transport_TKM", 60],
  ["CUP_I_LR_Transport_RACS", 60],
  ["CUP_I_LR_MG_RACS", 60],
  ["CUP_I_LR_Ambulance_RACS", 60],
  ["CUP_I_BRDM2_ATGM_NAPA", 30],
  ["CUP_I_BRDM2_ATGM_TK_Gue", 30],
  ["CUP_I_BRDM2_HQ_NAPA", 30],
  ["CUP_I_BRDM2_HQ_TK_Gue", 30],
  ["CUP_I_BRDM2_HQ_UN", 30],
  ["CUP_I_BRDM2_NAPA", 30],
  ["CUP_I_BRDM2_TK_Gue", 30],
  ["CUP_I_BRDM2_UN", 30],
  ["CUP_O_BRDM2_ATGM_CHDKZ", 30],
  ["CUP_O_BRDM2_ATGM_SLA", 30],
  ["CUP_O_BRDM2_ATGM_TKA", 30],
  ["CUP_O_BRDM2_CHDKZ", 30],
  ["CUP_O_BRDM2_HQ_CHDKZ", 30],
  ["CUP_O_BRDM2_HQ_SLA", 30],
  ["CUP_O_BRDM2_HQ_TKA", 30],
  ["CUP_O_BRDM2_SLA", 30],
  ["CUP_O_BRDM2_TKA", 30],
  ["CUP_B_BRDM2_ATGM_CDF", 30],
  ["CUP_B_BRDM2_CDF", 30],
  ["CUP_B_BRDM2_HQ_CDF", 30],
  ["CUP_B_LAV25M240_USMC", 30],
  ["CUP_B_LAV25_HQ_USMC", 30],
  ["CUP_B_LAV25_USMC", 30],
  ["CUP_B_BM21_CDF", 30],
  ["CUP_O_BM21_CHDKZ", 30],
  ["CUP_O_BM21_RU", 30],
  ["CUP_O_BM21_SLA", 30],
  ["CUP_O_BM21_TKA", 30],
  ["CUP_O_BTR60_TK", 30],
  ["CUP_O_BTR90_HQ_RU", 30],
  ["CUP_O_BTR90_RU", 30],
  ["CUP_C_Octavia_CIV", 60],
  ["CUP_C_Skoda_Red_Civ", 60],
  ["CUP_C_Skoda_White_Civ", 60],
  ["CUP_C_Skoda_Blue_Civ", 60],
  ["CUP_C_Skoda_Green_Civ", 60],
  ["CUP_C_Golf4_red_Civ", 60],
  ["CUP_C_Golf4_black_Civ", 60],
  ["CUP_C_Golf4_yellow_Civ", 60],
  ["CUP_C_Golf4_blue_Civ", 60],
  ["CUP_C_Golf4_white_Civ", 60],
  ["CUP_C_Golf4_green_Civ", 60],
  ["CUP_C_Golf4_random_Civ", 60],
  ["CUP_C_Golf4_whiteblood_Civ", 60],
  ["CUP_C_Golf4_camo_Civ", 60],
  ["CUP_C_Golf4_camodigital_Civ", 60],
  ["CUP_C_Golf4_camodark_Civ", 60],
  ["CUP_C_Golf4_reptile_Civ", 60],
  ["CUP_C_Golf4_kitty_Civ", 60],
  ["CUP_B_M1126_ICV_M2_Desert", 30],
  ["CUP_B_M1126_ICV_M2_Desert_Slat", 30],
  ["CUP_B_M1126_ICV_M2_Woodland", 30],
  ["CUP_B_M1126_ICV_M2_Woodland_Slat", 30],
  ["CUP_B_M1126_ICV_Mk19_Desert", 30],
  ["CUP_B_M1126_ICV_Mk19_Desert_Slat", 30],
  ["CUP_B_M1126_ICV_Mk19_Woodland", 30],
  ["CUP_B_M1126_ICV_Mk19_Woodland_Slat", 30],
  ["CUP_B_M1128_MGS_Desert", 30],
  ["CUP_B_M1128_MGS_Desert_Slat", 30],
  ["CUP_B_M1128_MGS_Woodland", 30],
  ["CUP_B_M1128_MGS_Woodland_Slat", 30],
  ["CUP_B_M1129_MC_MK19_Desert", 30],
  ["CUP_B_M1129_MC_MK19_Desert_Slat", 30],
  ["CUP_B_M1129_MC_MK19_Woodland", 30],
  ["CUP_B_M1129_MC_MK19_Woodland_Slat", 30],
  ["CUP_B_M1130_CV_M2_Desert", 30],
  ["CUP_B_M1130_CV_M2_Desert_Slat", 30],
  ["CUP_B_M1130_CV_M2_Woodland", 30],
  ["CUP_B_M1130_CV_M2_Woodland_Slat", 30],
  ["CUP_B_M1133_MEV_Desert", 30],
  ["CUP_B_M1133_MEV_Desert_Slat", 30],
  ["CUP_B_M1133_MEV_Woodland", 30],
  ["CUP_B_M1133_MEV_Woodland_Slat", 30],
  ["CUP_B_M1135_ATGMV_Desert", 30],
  ["CUP_B_M1135_ATGMV_Desert_Slat", 30],
  ["CUP_B_M1135_ATGMV_Woodland", 30],
  ["CUP_B_M1135_ATGMV_Woodland_Slat", 30],
  ["CUP_B_TowingTractor_USMC", 60],
  ["CUP_B_AAV_USMC", 30],
  ["CUP_B_M113_Med_USA", 30],
  ["CUP_B_M113_USA", 30],
  ["CUP_I_M113_Med_RACS", 30],
  ["CUP_I_M113_Med_UN", 30],
  ["CUP_I_M113_RACS", 30],
  ["CUP_I_M113_UN", 30],
  ["CUP_O_M113_Med_TKA", 30],
  ["CUP_O_M113_TKA", 30],
  ["CUP_B_M163_USA", 30],
  ["CUP_I_M163_RACS", 30],
  ["CUP_B_M1A1_DES_USMC", 30],
  ["CUP_B_M1A1_DES_US_Army", 30],
  ["CUP_B_M1A1_Woodland_USMC", 30],
  ["CUP_B_M1A1_Woodland_US_Army", 30],
  ["CUP_B_M1A2_TUSK_MG_DES_USMC", 30],
  ["CUP_B_M1A2_TUSK_MG_DES_US_Army", 30],
  ["CUP_B_M1A2_TUSK_MG_USMC", 30],
  ["CUP_B_M1A2_TUSK_MG_US_Army", 30],
  ["CUP_B_M270_DPICM_USA", 30],
  ["CUP_B_M270_DPICM_USMC", 30],
  ["CUP_B_M270_HE_USA", 30],
  ["CUP_B_M270_HE_USMC", 30],
  ["CUP_B_M2Bradley_USA_D", 30],
  ["CUP_B_M2Bradley_USA_W", 30],
  ["CUP_B_M2A3Bradley_USA_D", 30],
  ["CUP_B_M2A3Bradley_USA_W", 30],
  ["CUP_I_T55_TK_GUE", 30],
  ["CUP_O_T55_TK", 30],
  ["CUP_O_T72_CHDKZ", 30],
  ["CUP_O_T72_RU", 30],
  ["CUP_O_T72_SLA", 30],
  ["CUP_O_T72_TKA", 30],
  ["CUP_B_T72_CDF", 30],
  ["CUP_I_T72_NAPA", 30],
  ["CUP_I_T72_RACS", 30],
  ["CUP_B_ZSU23_CDF", 30],
  ["CUP_O_ZSU23_ChDKZ", 30],
  ["CUP_O_ZSU23_SLA", 30],
  ["CUP_O_ZSU23_TK", 30],
  ["CUP_T34_BASE", 30],
  ["CUP_I_T34_NAPA", 30],
  ["CUP_I_T34_TK_GUE", 30],
  ["CUP_O_T34_TKA", 30],
  ["CUP_B_FV432_Bulldog_GB_W_RWS", 30],
  ["CUP_B_Dingo_GER_Wdl", 90],
  ["CUP_B_Mastiff_HMG_GB_W", 90],
  ["CUP_B_Ridgback_HMG_GB_W", 90],
  ["CUP_I_BTR40_TKG", 60],
  ["CUP_I_SUV_Armored_ION", 60],
  ["CUP_O_GAZ_Vodnik_PK_RU", 90],
  ["CUP_B_BAF_Coyote_L2A1_W", 90],
  ["CUP_B_BAF_Coyote_L2A1_D", 90],
  ["CUP_O_UH1H_SLA", 60],
  ["CUP_O_UH1H_TKA", 60]

];

/**
 * List of class names of objects which can be loaded in transport vehicle/cargo.
 * The second element of the nested arrays is the cost capacity (in relation with the capacity of the vehicles).
 *
 * Liste des noms de classes des objets transportables.
 * Le deuxième élément des sous-tableaux est le coût de capacité (en relation avec la capacité des véhicules).
 */
R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	// e.g. : ["MyTransportableObjectClassName1", itsCost], ["MyTransportableObjectClassName2", itsCost]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

/**
 * List of class names of objects which can be carried and moved by a player.
 * Liste des noms de classes des objets qui peuvent être portés et déplacés par le joueur.
 */
R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	// e.g. : "MyMovableObjectClassName1", "MyMovableObjectClassName2"
];
