R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[


"Exile_Car_OldTractor_Red",
"Exile_Car_TowTractor_White",
"Exile_Car_Tractor_Red",
"Exile_Car_UAZ_Green",
"Exile_Car_UAZ_Open_Green",
"Exile_Car_Octavius_White",
"Exile_Car_Golf_Red",
"Exile_Car_LandRover_Green",
"Exile_Car_LandRover_Ambulance_Green",
"Exile_Car_Lada_Green",
"Exile_Car_Lada_White",
"Exile_Car_Lada_Taxi",
"Exile_Car_Lada_Hipster",
"Exile_Car_Volha_White",
"Exile_Car_Volha_Blue",
"Exile_Car_Volha_Black",
"Exile_Car_Hatchback_Sport_Red",
"Exile_Car_Hatchback_Sport_Blue",
"Exile_Car_Hatchback_Sport_Orange",
"Exile_Car_Hatchback_Sport_White",
"Exile_Car_Hatchback_Sport_Beige",
"Exile_Car_Hatchback_Sport_Green",
"Exile_Car_Hatchback_Green",
"Exile_Car_Hatchback_BlueCustom",
"Exile_Car_Hatchback_BeigeCustom",
"Exile_Car_Hatchback_Yellow",
"Exile_Car_Hatchback_Grey",
"Exile_Car_Hatchback_Black",
"Exile_Car_Hatchback_Dark",
"Exile_Car_Hatchback_Beige",
"Exile_Car_Hatchback_Green",
"Exile_Car_Hatchback_Blue",
"Exile_Car_Hatchback_Rusty1",
"Exile_Car_Hatchback_Rusty2",
"Exile_Car_Hatchback_Rusty3",
"Exile_Car_SUV_Red",
"Exile_Car_SUVXL_Black",
"Exile_Car_SUV_Armed_Black",
"Exile_Car_Offroad_Red",
"Exile_Car_Offroad_Beige",
"Exile_Car_Offroad_White",
"Exile_Car_Offroad_Blue",
"Exile_Car_Offroad_DarkRed",
"Exile_Car_Offroad_BlueCustom",
"Exile_Car_Offroad_Armed_Guerilla01",
"Exile_Car_Offroad_Guerilla01",
"Exile_Car_Offroad_Guerilla02",
"Exile_Car_Offroad_Guerilla03",
"Exile_Car_Offroad_Guerilla04",
"Exile_Car_Offroad_Guerilla05",
"Exile_Car_Offroad_Guerilla06",
"Exile_Car_Offroad_Guerilla07",
"Exile_Car_Offroad_Guerilla08",
"Exile_Car_Offroad_Guerilla09",
"Exile_Car_Offroad_Guerilla10",
"Exile_Car_Offroad_Guerilla11",
"Exile_Car_Offroad_Guerilla12",
"Exile_Car_Offroad_Rusty1",
"Exile_Car_Offroad_Rusty2",
"Exile_Car_Offroad_Rusty3",
"Exile_Car_Offroad_Repair_Civillian",
"Exile_Car_BRDM2_HQ",
"Exile_Car_BTR40_MG_Green",
"Exile_Car_BTR40_Green",
"Exile_Car_BTR40_MG_Camo",
"Exile_Car_HMMWV_M134_Green",
"Exile_Car_HMMWV_M2_Desert",
"Exile_Car_HMMWV_M134_Desert",
"Exile_Car_HMMWV_M2_Green",
"Exile_Car_HMMWV_MEV_Green",
"Exile_Car_HMMWV_UNA_Green",
"Exile_Car_Strider",
"Exile_Car_Hunter",
"Exile_Car_Ifrit",
"Exile_Car_Van_Black",
"Exile_Car_Van_Box_Black",
"Exile_Car_Van_Fuel_Black",
"Exile_Car_Ural_Open_Blue",
"Exile_Car_Ural_Open_Yellow",
"Exile_Car_Ural_Open_Worker",
"Exile_Car_Ural_Open_Military",
"Exile_Car_Ural_Covered_Blue",
"Exile_Car_Ural_Covered_Yellow",
"Exile_Car_Ural_Covered_Worker",
"Exile_Car_Ural_Covered_Military",
"Exile_Car_V3S_Covered",
"Exile_Car_Zamak",
"Exile_Car_Tempest",
"Exile_Car_HEMMT",
"Exile_Car_Ikarus_Blue"


];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
"Exile_Car_Kart_Black",
"Exile_Bike_QuadBike_Black",
"Exile_Car_OldTractor_Red",
"Exile_Car_TowTractor_White",
"Exile_Car_Tractor_Red",
"Exile_Car_UAZ_Green",
"Exile_Car_UAZ_Open_Green",
"Exile_Car_Octavius_White",
"Exile_Car_Golf_Red",
"Exile_Car_LandRover_Green",
"Exile_Car_LandRover_Ambulance_Green",
"Exile_Car_Lada_Green",
"Exile_Car_Lada_White",
"Exile_Car_Lada_Taxi",
"Exile_Car_Lada_Hipster",
"Exile_Car_Volha_White",
"Exile_Car_Volha_Blue",
"Exile_Car_Volha_Black",
"Exile_Car_Hatchback_Sport_Red",
"Exile_Car_Hatchback_Sport_Blue",
"Exile_Car_Hatchback_Sport_Orange",
"Exile_Car_Hatchback_Sport_White",
"Exile_Car_Hatchback_Sport_Beige",
"Exile_Car_Hatchback_Sport_Green",
"Exile_Car_Hatchback_Green",
"Exile_Car_Hatchback_BlueCustom",
"Exile_Car_Hatchback_BeigeCustom",
"Exile_Car_Hatchback_Yellow",
"Exile_Car_Hatchback_Grey",
"Exile_Car_Hatchback_Black",
"Exile_Car_Hatchback_Dark",
"Exile_Car_Hatchback_Beige",
"Exile_Car_Hatchback_Green",
"Exile_Car_Hatchback_Blue",
"Exile_Car_Hatchback_Rusty1",
"Exile_Car_Hatchback_Rusty2",
"Exile_Car_Hatchback_Rusty3",
"Exile_Car_SUV_Red",
"Exile_Car_SUVXL_Black",
"Exile_Car_SUV_Armed_Black",
"Exile_Car_Offroad_Red",
"Exile_Car_Offroad_Beige",
"Exile_Car_Offroad_White",
"Exile_Car_Offroad_Blue",
"Exile_Car_Offroad_DarkRed",
"Exile_Car_Offroad_BlueCustom",
"Exile_Car_Offroad_Armed_Guerilla01",
"Exile_Car_Offroad_Guerilla01",
"Exile_Car_Offroad_Guerilla02",
"Exile_Car_Offroad_Guerilla03",
"Exile_Car_Offroad_Guerilla04",
"Exile_Car_Offroad_Guerilla05",
"Exile_Car_Offroad_Guerilla06",
"Exile_Car_Offroad_Guerilla07",
"Exile_Car_Offroad_Guerilla08",
"Exile_Car_Offroad_Guerilla09",
"Exile_Car_Offroad_Guerilla10",
"Exile_Car_Offroad_Guerilla11",
"Exile_Car_Offroad_Guerilla12",
"Exile_Car_Offroad_Rusty1",
"Exile_Car_Offroad_Rusty2",
"Exile_Car_Offroad_Rusty3",
"Exile_Car_Offroad_Repair_Civillian",
"Exile_Car_BRDM2_HQ",
"Exile_Car_BTR40_MG_Green",
"Exile_Car_BTR40_Green",
"Exile_Car_BTR40_MG_Camo",
"Exile_Car_HMMWV_M134_Green",
"Exile_Car_HMMWV_M2_Desert",
"Exile_Car_HMMWV_M134_Desert",
"Exile_Car_HMMWV_M2_Green",
"Exile_Car_HMMWV_MEV_Green",
"Exile_Car_HMMWV_UNA_Green",
"Exile_Car_Strider",
"Exile_Car_Hunter",
"Exile_Car_Ifrit",
"Exile_Car_Van_Black",
"Exile_Car_Van_Box_Black",
"Exile_Car_Van_Fuel_Black",
"Exile_Car_Ural_Open_Worker",
"Exile_Car_Ural_Covered_Worker",
"Exile_Car_Ural_Covered_Military",
"Exile_Car_Ural_Covered_Blue",
"Exile_Car_Ural_Covered_Yellow",
"Exile_Car_V3S_Covered",
"Exile_Car_Zamak",
"Exile_Car_Tempest",
"Exile_Car_HEMMT",
"Exile_Car_Ikarus_Blue"
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[

		"Exile_Chopper_Hummingbird_Green",
		"Exile_Chopper_Hummingbird_Civillian_Blue",			
		"Exile_Chopper_Hummingbird_Civillian_BlueLine",		
		"Exile_Chopper_Hummingbird_Civillian_Digital",			
		"Exile_Chopper_Hummingbird_Civillian_Elliptical",		
		"Exile_Chopper_Hummingbird_Civillian_Furious",		
		"Exile_Chopper_Hummingbird_Civillian_GrayWatcher",
		"Exile_Chopper_Hummingbird_Civillian_ION",			
		"Exile_Chopper_Hummingbird_Civillian_Jeans",			
		"Exile_Chopper_Hummingbird_Civillian_Light",			
		"Exile_Chopper_Hummingbird_Civillian_Red",				
		"Exile_Chopper_Hummingbird_Civillian_Shadow",		
		"Exile_Chopper_Hummingbird_Civillian_Sheriff",			
		"Exile_Chopper_Hummingbird_Civillian_Speedy",		
		"Exile_Chopper_Hummingbird_Civillian_Sunset",		
		"Exile_Chopper_Hummingbird_Civillian_Vrana",			
		"Exile_Chopper_Hummingbird_Civillian_Wasp",			
		"Exile_Chopper_Hummingbird_Civillian_Wave",			
		"Exile_Chopper_Huey_Green",
		"Exile_Chopper_Huey_Armed_Green",
		"Exile_Chopper_Huey_Desert",					
        "Exile_Chopper_Huey_Armed_Desert",
		"Exile_Chopper_Taru_Black",
		"Exile_Chopper_Taru_Covered_Black",
		"Exile_Chopper_Taru_Transport_Black",
		"Exile_Chopper_Taru_CSAT",
		"Exile_Chopper_Taru_Covered_CSAT",
		"Exile_Chopper_Taru_Transport_CSAT",
		"Exile_Chopper_Orca_CSAT",
		"Exile_Chopper_Orca_BlackCustom",
		"Exile_Chopper_Orca_Black",
		"Exile_Chopper_Mohawk_FIA",
		"Exile_Chopper_Huron_Black",
		"Exile_Chopper_Huron_Green",
		"Exile_Chopper_Hellcat_Green",
		"Exile_Chopper_Hellcat_FIA"
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
"Exile_Car_Kart_Black",
"Exile_Bike_QuadBike_Black",
"Exile_Car_OldTractor_Red",
"Exile_Car_TowTractor_White",
"Exile_Car_Tractor_Red",
"Exile_Car_UAZ_Green",
"Exile_Car_UAZ_Open_Green",
"Exile_Car_Octavius_White",
"Exile_Car_Golf_Red",
"Exile_Car_LandRover_Green",
"Exile_Car_LandRover_Ambulance_Green",
"Exile_Car_Lada_Green",
"Exile_Car_Lada_White",
"Exile_Car_Lada_Taxi",
"Exile_Car_Lada_Hipster",
"Exile_Car_Volha_White",
"Exile_Car_Volha_Blue",
"Exile_Car_Volha_Black",
"Exile_Car_Hatchback_Sport_Red",
"Exile_Car_Hatchback_Sport_Blue",
"Exile_Car_Hatchback_Sport_Orange",
"Exile_Car_Hatchback_Sport_White",
"Exile_Car_Hatchback_Sport_Beige",
"Exile_Car_Hatchback_Sport_Green",
"Exile_Car_Hatchback_Green",
"Exile_Car_Hatchback_BlueCustom",
"Exile_Car_Hatchback_BeigeCustom",
"Exile_Car_Hatchback_Yellow",
"Exile_Car_Hatchback_Grey",
"Exile_Car_Hatchback_Black",
"Exile_Car_Hatchback_Dark",
"Exile_Car_Hatchback_Beige",
"Exile_Car_Hatchback_Green",
"Exile_Car_Hatchback_Blue",
"Exile_Car_Hatchback_Rusty1",
"Exile_Car_Hatchback_Rusty2",
"Exile_Car_Hatchback_Rusty3",
"Exile_Car_SUV_Red",
"Exile_Car_SUVXL_Black",
"Exile_Car_SUV_Armed_Black",
"Exile_Car_Offroad_Red",
"Exile_Car_Offroad_Beige",
"Exile_Car_Offroad_White",
"Exile_Car_Offroad_Blue",
"Exile_Car_Offroad_DarkRed",
"Exile_Car_Offroad_BlueCustom",
"Exile_Car_Offroad_Armed_Guerilla01",
"Exile_Car_Offroad_Guerilla01",
"Exile_Car_Offroad_Guerilla02",
"Exile_Car_Offroad_Guerilla03",
"Exile_Car_Offroad_Guerilla04",
"Exile_Car_Offroad_Guerilla05",
"Exile_Car_Offroad_Guerilla06",
"Exile_Car_Offroad_Guerilla07",
"Exile_Car_Offroad_Guerilla08",
"Exile_Car_Offroad_Guerilla09",
"Exile_Car_Offroad_Guerilla10",
"Exile_Car_Offroad_Guerilla11",
"Exile_Car_Offroad_Guerilla12",
"Exile_Car_Offroad_Rusty1",
"Exile_Car_Offroad_Rusty2",
"Exile_Car_Offroad_Rusty3",
"Exile_Car_Offroad_Repair_Civillian",
"Exile_Car_BRDM2_HQ",
"Exile_Car_BTR40_MG_Green",
"Exile_Car_BTR40_Green",
"Exile_Car_BTR40_MG_Camo",
"Exile_Car_HMMWV_M134_Green",
"Exile_Car_HMMWV_M2_Desert",
"Exile_Car_HMMWV_M134_Desert",
"Exile_Car_HMMWV_M2_Green",
"Exile_Car_HMMWV_MEV_Green",
"Exile_Car_HMMWV_UNA_Green",
"Exile_Car_Strider",
"Exile_Car_Hunter",
"Exile_Car_Ifrit",
"Exile_Car_Van_Black",
"Exile_Car_Van_Box_Black",
"Exile_Car_Van_Fuel_Black",
"Exile_Car_Ural_Open_Worker",
"Exile_Car_Ural_Covered_Worker",
"Exile_Car_Ural_Covered_Military",
"Exile_Car_Ural_Covered_Blue",
"Exile_Car_Ural_Covered_Yellow",
"Exile_Car_V3S_Covered",
"Exile_Car_Zamak",
"Exile_Car_Tempest",
"Exile_Car_HEMMT",
"Exile_Car_Ikarus_Blue"
];



R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[

			
			["Exile_Car_Kart_Black", 60],
			["Exile_Bike_QuadBike_Black", 60],
			["Exile_Car_OldTractor_Red", 60],
			["Exile_Car_TowTractor_White", 60],
			["Exile_Car_Tractor_Red", 60],
			["Exile_Car_UAZ_Green", 60],
			["Exile_Car_UAZ_Open_Green", 60],
			["Exile_Car_Octavius_White", 60],
			["Exile_Car_Golf_Red", 60],
			["Exile_Car_LandRover_Green", 60],
			["Exile_Car_LandRover_Ambulance_Green", 60],
			["Exile_Car_Lada_Green", 60],
			["Exile_Car_Lada_White", 60],
			["Exile_Car_Lada_Taxi", 60],
			["Exile_Car_Lada_Hipster", 60],
			["Exile_Car_Volha_White", 60],
			["Exile_Car_Volha_Blue", 60],
			["Exile_Car_Volha_Black", 60],
			["Exile_Car_Hatchback_Sport_Red", 60],
			["Exile_Car_Hatchback_Sport_Blue", 60],
			["Exile_Car_Hatchback_Sport_Orange", 60],
			["Exile_Car_Hatchback_Sport_White", 60],
			["Exile_Car_Hatchback_Sport_Beige", 60],
			["Exile_Car_Hatchback_Sport_Green", 60],
			["Exile_Car_Hatchback_Green", 60],
			["Exile_Car_Hatchback_BlueCustom", 60],
			["Exile_Car_Hatchback_BeigeCustom", 60],
			["Exile_Car_Hatchback_Yellow", 60],
			["Exile_Car_Hatchback_Grey", 60],
			["Exile_Car_Hatchback_Black", 60],
			["Exile_Car_Hatchback_Dark", 60],
			["Exile_Car_Hatchback_Beige", 60],
			["Exile_Car_Hatchback_Green", 60],
			["Exile_Car_Hatchback_Blue", 60],
			["Exile_Car_Hatchback_Rusty1", 60],
			["Exile_Car_Hatchback_Rusty2", 60],
			["Exile_Car_Hatchback_Rusty3", 60],
			["Exile_Car_SUV_Red", 60],
			["Exile_Car_SUVXL_Black", 60],
			["Exile_Car_SUV_Armed_Black", 60],
			["Exile_Car_Offroad_Red", 60],
			["Exile_Car_Offroad_Beige", 60],
			["Exile_Car_Offroad_White", 60],
			["Exile_Car_Offroad_Blue", 60],
			["Exile_Car_Offroad_DarkRed", 60],
			["Exile_Car_Offroad_BlueCustom", 60],
			["Exile_Car_Offroad_Armed_Guerilla01",60],
			["Exile_Car_Offroad_Guerilla01", 60],
			["Exile_Car_Offroad_Guerilla02", 60],
			["Exile_Car_Offroad_Guerilla03", 60],
			["Exile_Car_Offroad_Guerilla04", 60],
			["Exile_Car_Offroad_Guerilla05", 60],
			["Exile_Car_Offroad_Guerilla06", 60],
			["Exile_Car_Offroad_Guerilla07", 60],
			["Exile_Car_Offroad_Guerilla08", 60],
			["Exile_Car_Offroad_Guerilla09", 60],
			["Exile_Car_Offroad_Guerilla10", 60],
			["Exile_Car_Offroad_Guerilla11", 60],
			["Exile_Car_Offroad_Guerilla12", 60],
			["Exile_Car_Offroad_Rusty1", 60],
			["Exile_Car_Offroad_Rusty2", 60],
			["Exile_Car_Offroad_Rusty3", 60],
			["Exile_Car_Offroad_Repair_Civillian", 60],
			["Exile_Car_BRDM2_HQ", 60],
			["Exile_Car_BTR40_MG_Green", 60],
			["Exile_Car_BTR40_Green", 60],
			["Exile_Car_BTR40_MG_Camo", 60],
			["Exile_Car_HMMWV_M2_Desert", 60],			
			["Exile_Car_HMMWV_M134_Green", 60],
			["Exile_Car_HMMWV_M134_Desert", 60],
			["Exile_Car_HMMWV_M2_Green", 60],
			["Exile_Car_HMMWV_MEV_Green", 60],
			["Exile_Car_HMMWV_UNA_Green", 60],
			["Exile_Car_Strider", 60],
			["Exile_Car_Hunter", 60],
			["Exile_Car_Ifrit", 60],
			["Exile_Car_Van_Black", 60],
			["Exile_Car_Van_Box_Black", 60],
			["Exile_Car_Van_Fuel_Black", 60],
			["Exile_Car_Ural_Open_Worker", 60],
			["Exile_Car_Ural_Covered_Worker", 60],
			["Exile_Car_Ural_Covered_Military", 60],
			["Exile_Car_Ural_Covered_Blue", 60],
			["Exile_Car_Ural_Covered_Yellow", 60],
			["Exile_Car_V3S_Covered", 60],
			["Exile_Car_Zamak", 60],
			["Exile_Car_Tempest", 60],
			["Exile_Car_HEMMT", 60],
			["Exile_Car_Ikarus_Blue", 60],
			["Exile_Chopper_Hummingbird_Green", 60],
			["Exile_Chopper_Hummingbird_Civillian_Blue", 60],			
			["Exile_Chopper_Hummingbird_Civillian_BlueLine", 60],		
			["Exile_Chopper_Hummingbird_Civillian_Digital", 60],			
			["Exile_Chopper_Hummingbird_Civillian_Elliptical", 60],		
			["Exile_Chopper_Hummingbird_Civillian_Furious", 60],		
			["Exile_Chopper_Hummingbird_Civillian_GrayWatcher", 60],
			["Exile_Chopper_Hummingbird_Civillian_ION", 60],			
			["Exile_Chopper_Hummingbird_Civillian_Jeans", 60],		
			["Exile_Chopper_Hummingbird_Civillian_Light", 60],		
			["Exile_Chopper_Hummingbird_Civillian_Red", 60],				
			["Exile_Chopper_Hummingbird_Civillian_Shadow", 60],		
			["Exile_Chopper_Hummingbird_Civillian_Sheriff", 60],			
			["Exile_Chopper_Hummingbird_Civillian_Speedy", 60],		
			["Exile_Chopper_Hummingbird_Civillian_Sunset", 60],		
			["Exile_Chopper_Hummingbird_Civillian_Vrana", 60],			
			["Exile_Chopper_Hummingbird_Civillian_Wasp", 60],			
			["Exile_Chopper_Hummingbird_Civillian_Wave", 60],			
			["Exile_Chopper_Huey_Green", 60],
			["Exile_Chopper_Huey_Armed_Green", 60],
			["Exile_Chopper_Huey_Desert", 60],					
			["Exile_Chopper_Huey_Armed_Desert", 60],
			["Exile_Chopper_Taru_Black", 60],
			["Exile_Chopper_Taru_Covered_Black", 60],
			["Exile_Chopper_Taru_Transport_Black", 60],
			["Exile_Chopper_Taru_CSAT", 60],
			["Exile_Chopper_Taru_Covered_CSAT", 60],
			["Exile_Chopper_Taru_Transport_CSAT", 60],
			["Exile_Chopper_Orca_CSAT", 60],
			["Exile_Chopper_Orca_BlackCustom", 60],
			["Exile_Chopper_Orca_Black", 60],
			["Exile_Chopper_Mohawk_FIA", 60],
			["Exile_Chopper_Huron_Black", 120],
			["Exile_Chopper_Huron_Green", 120],
			["Exile_Chopper_Hellcat_Green", 60],
			["Exile_Chopper_Hellcat_FIA", 60],
			["Exile_Boat_MotorBoat_Orange", 60],
			["Exile_Boat_MotorBoat_Police", 60],
			["Exile_Boat_MotorBoat_White", 60],
			["Exile_Boat_RHIB", 60],
			["Exile_Boat_RubberDuck_Black", 60],
			["Exile_Boat_RubberDuck_Blue", 60],
			["Exile_Boat_RubberDuck_CSAT", 60],
			["Exile_Boat_RubberDuck_Digital", 60],
			["Exile_Boat_RubberDuck_Orange", 60],
			["Exile_Boat_SDV_CSAT", 60],
			["Exile_Boat_SDV_Digital", 60],
			["Exile_Boat_SDV_Grey", 60],
			["Exile_Boat_WaterScooter", 60],
			["Exile_Plane_AN2_Green", 60],
			["Exile_Plane_BlackfishInfantry", 60],
			["Exile_Plane_BlackfishVehicle", 60],
			["Exile_Plane_Ceasar", 60],
			["Exile_Plane_Cessna", 60],
			["RwG_Mozzie_Carl_Red",  40],
			["RwG_Mozzie_Carl_Blue",  40],
			["RwG_Mozzie_Carl_Green",  40],
			["RwG_Mozzie_Carl_Pink",  40],
			["RwG_Mozzie_Carl_Yellow",  40],
			["RwG_Mozzie_Carl_Black",  40],
			["RwG_Mozzie_Carl_White",  40],
			["RwG_Mozzie_Carl_Orange",  40],
			["RwG_Mozzie_Carl_Gold",  40]

			
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[

];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
];
