/**
 * English and French comments
 * Commentaires anglais et français
 *
 * This file is a template to add objetcs from an addon in the configuration variables of the logistics system.
 * Make a copy of this file and fill it. Then add a #include to this file in the file R3F_LOG\config.sqf.
 *
 * IMPORTANT NOTE : when a logistics feature is given to an object/vehicle class name, all the classes which inherit
 *                  of the parent/generic class (according to the CfgVehicles) will also have this feature.
 *                  CfgVehicles tree view example : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 *
 *
 * Ce fichier est un exemple vierge permettant d'ajouter des objets d'un addon dans la configuration du système de logistique.
 * Faites une copie de ce fichier et remplissez-le. Puis ajouter un #include vers celui-ci dans le fichier R3F_LOG\config.sqf.
 *
 * NOTE IMPORTANTE : lorsqu'une fonctionnalité logistique est accordée à un nom de classe d'objet/véhicule, les classes
 *                   héritant de cette classe mère/générique (selon le CfgVehicles) se verront également dotées de cette fonctionnalité.
 *                   Exemple d'arborescence du CfgVehicles : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 */

/**
 * List of class names of ground vehicles which can tow objects.
 * Liste des noms de classes des véhicules terrestres pouvant remorquer des objets.
 */
R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
	
            "FMP_Hunter_Ocamo",
            "FMP_Hunter_Skull",
            "FMP_Hunter_Savage",
            "FMP_Hunter_Alpha",
            "FMP_Hunter_Suba",
            "FMP_Hunter_Milsim",
            "FMP_Hunter_Grunge",
            "FMP_Hunter_Bgcamo",
            "FMP_Strider_Splatter",
            "FMP_Strider_Carbon",
            "FMP_Strider_Radioactive",
            "FMP_Strider_Rusty",
            "FMP_Strider_Multi",
            "FMP_Strider_Hex",
            "FMP_Strider_Standard",
            "bv_458_black2",
            "bv_458_aqua",
            "bv_458_baby_blue",
            "bv_458_baby_pink",
            "bv_458_burgundy",
            "bv_458_cardinal",
            "bv_458_dark_green",
            "bv_458_gold",
            "bv_458_green",
            "bv_458_grey",
            "bv_458_lavender",
            "bv_458_light_blue",
            "bv_458_light_yellow",
            "bv_458_lime",
            "bv_458_marina_blue",
            "bv_458_navy_blue",
            "bv_458_orange",
            "bv_458_pink",
            "bv_458_purple",
            "bv_458_red",
            "bv_458_sand",
            "bv_458_silver",
            "bv_458_skin_blue",
            "bv_458_skin_camo",
            "bv_458_skin_camo_urban",
            "bv_ben_dover_black2",
            "bv_ben_dover_aqua",
            "bv_ben_dover_baby_blue",
            "bv_ben_dover_baby_pink",
            "bv_ben_dover_burgundy",
            "bv_ben_dover_cardinal",
            "bv_ben_dover_dark_green",
            "bv_ben_dover_gold",
            "bv_ben_dover_green",
            "bv_ben_dover_grey",
            "bv_ben_dover_lavender",
            "bv_ben_dover_light_blue",
            "bv_ben_dover_light_yellow",
            "bv_ben_dover_lime",
            "bv_ben_dover_marina_blue",
            "bv_ben_dover_navy_blue",
            "bv_ben_dover_orange",
            "bv_ben_dover_pink",
            "bv_ben_dover_purple",
            "bv_ben_dover_red",
            "bv_ben_dover_sand",
            "bv_ben_dover_silver",
            "bv_ben_dover_skin_blue",
            "bv_ben_dover_skin_camo",
            "bv_ben_dover_skin_camo_urban",
            "bv_caressa_gt_black2",
            "bv_caressa_gt_aqua",
            "bv_caressa_gt_baby_blue",
            "bv_caressa_gt_baby_pink",
            "bv_caressa_gt_burgundy",
            "bv_caressa_gt_cardinal",
            "bv_caressa_gt_dark_green",
            "bv_caressa_gt_gold",
            "bv_caressa_gt_green",
            "bv_caressa_gt_grey",
            "bv_caressa_gt_lavender",
            "bv_caressa_gt_light_blue",
            "bv_caressa_gt_light_yellow",
            "bv_caressa_gt_lime",
            "bv_caressa_gt_marina_blue",
            "bv_caressa_gt_navy_blue",
            "bv_caressa_gt_orange",
            "bv_caressa_gt_pink",
            "bv_caressa_gt_purple",
            "bv_caressa_gt_red",
            "bv_caressa_gt_sand",
            "bv_caressa_gt_silver",
            "bv_caressa_gt_skin_blue",
            "bv_caressa_gt_skin_camo",
            "bv_caressa_gt_skin_camo_urban",
            "bv_e60_m5_black2",
            "bv_e60_m5_aqua",
            "bv_e60_m5_baby_blue",
            "bv_e60_m5_baby_pink",
            "bv_e60_m5_burgundy",
            "bv_e60_m5_cardinal",
            "bv_e60_m5_dark_green",
            "bv_e60_m5_gold",
            "bv_e60_m5_green",
            "bv_e60_m5_grey",
            "bv_e60_m5_lavender",
            "bv_e60_m5_light_blue",
            "bv_e60_m5_light_yellow",
            "bv_e60_m5_lime",
            "bv_e60_m5_marina_blue",
            "bv_e60_m5_navy_blue",
            "bv_e60_m5_orange",
            "bv_e60_m5_pink",
            "bv_e60_m5_purple",
            "bv_e60_m5_red",
            "bv_e60_m5_sand",
            "bv_e60_m5_silver",
            "bv_e60_m5_skin_blue",
            "bv_e60_m5_skin_camo",
            "bv_e60_m5_skin_camo_urban",
            "bv_e63_amg_black2",
            "bv_e63_amg_aqua",
            "bv_e63_amg_baby_blue",
            "bv_e63_amg_baby_pink",
            "bv_e63_amg_burgundy",
            "bv_e63_amg_cardinal",
            "bv_e63_amg_dark_green",
            "bv_e63_amg_gold",
            "bv_e63_amg_green",
            "bv_e63_amg_grey",
            "bv_e63_amg_lavender",
            "bv_e63_amg_light_blue",
            "bv_e63_amg_light_yellow",
            "bv_e63_amg_lime",
            "bv_e63_amg_marina_blue",
            "bv_e63_amg_navy_blue",
            "bv_e63_amg_orange",
            "bv_e63_amg_pink",
            "bv_e63_amg_purple",
            "bv_e63_amg_red",
            "bv_e63_amg_sand",
            "bv_e63_amg_silver",
            "bv_e63_amg_skin_blue",
            "bv_e63_amg_skin_camo",
            "bv_e63_amg_skin_camo_urban",
            "bv_gtr_spec_V_black2",
            "bv_gtr_spec_V_aqua",
            "bv_gtr_spec_V_baby_blue",
            "bv_gtr_spec_V_baby_pink",
            "bv_gtr_spec_V_burgundy",
            "bv_gtr_spec_V_cardinal",
            "bv_gtr_spec_V_dark_green",
            "bv_gtr_spec_V_gold",
            "bv_gtr_spec_V_green",
            "bv_gtr_spec_V_grey",
            "bv_gtr_spec_V_lavender",
            "bv_gtr_spec_V_light_blue",
            "bv_gtr_spec_V_light_yellow",
            "bv_gtr_spec_V_lime",
            "bv_gtr_spec_V_marina_blue",
            "bv_gtr_spec_V_navy_blue",
            "bv_gtr_spec_V_orange",
            "bv_gtr_spec_V_pink",
            "bv_gtr_spec_V_purple",
            "bv_gtr_spec_V_red",
            "bv_gtr_spec_V_sand",
            "bv_gtr_spec_V_silver",
            "bv_gtr_spec_V_skin_blue",
            "bv_gtr_spec_V_skin_camo",
            "bv_gtr_spec_V_skin_camo_urban",
            "bv_shelly_bf_skin",
            "bv_shelly_bw_skin",
            "bv_shelly_rw_skin",
            "bv_shelly_wb_skin",
            "bv_shelly_wbl_skin",
            "bv_shelly_wf_skin",
            "bv_the_crowner_black2",
            "bv_the_crowner_aqua",
            "bv_the_crowner_baby_blue",
            "bv_the_crowner_baby_pink",
            "bv_the_crowner_burgundy",
            "bv_the_crowner_cardinal",
            "bv_the_crowner_dark_green",
            "bv_the_crowner_gold",
            "bv_the_crowner_green",
            "bv_the_crowner_grey",
            "bv_the_crowner_lavender",
            "bv_the_crowner_light_blue",
            "bv_the_crowner_light_yellow",
            "bv_the_crowner_lime",
            "bv_the_crowner_marina_blue",
            "bv_the_crowner_navy_blue",
            "bv_the_crowner_orange",
            "bv_the_crowner_pink",
            "bv_the_crowner_purple",
            "bv_the_crowner_red",
            "bv_the_crowner_sand",
            "bv_the_crowner_silver",
            "bv_the_crowner_skin_blue",
            "bv_the_crowner_skin_camo",
            "bv_the_crowner_skin_camo_urban",
            "bv_the_crowner_skin_white",
            "bv_monster_black2",
            "bv_monster_aqua",
            "bv_monster_baby_blue",
            "bv_monster_baby_pink",
            "bv_monster_burgundy",
            "bv_monster_cardinal",
            "bv_monster_dark_green",
            "bv_monster_gold",
            "bv_monster_green",
            "bv_monster_grey",
            "bv_monster_lavender",
            "bv_monster_light_blue",
            "bv_monster_light_yellow",
            "bv_monster_lime",
            "bv_monster_marina_blue",
            "bv_monster_navy_blue",
            "bv_monster_orange",
            "bv_monster_pink",
            "bv_monster_purple",
            "bv_monster_red",
            "bv_monster_sand",
            "bv_monster_silver",
            "bv_monster_skin_blue",
            "bv_monster_skin_camo",
            "bv_monster_skin_camo_urban"
];

/**
 * List of class names of objects which can be towed.
 * Liste des noms de classes des objets remorquables.
 */
R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
	        "FMP_Hunter_Ocamo",
            "FMP_Hunter_Skull",
            "FMP_Hunter_Savage",
            "FMP_Hunter_Alpha",
            "FMP_Hunter_Suba",
            "FMP_Hunter_Milsim",
            "FMP_Hunter_Grunge",
            "FMP_Hunter_Bgcamo",
            "FMP_Strider_Splatter",
            "FMP_Strider_Carbon",
            "FMP_Strider_Radioactive",
            "FMP_Strider_Rusty",
            "FMP_Strider_Multi",
            "FMP_Strider_Hex",
            "FMP_Strider_Standard",
            "bv_458_black2",
            "bv_458_aqua",
            "bv_458_baby_blue",
            "bv_458_baby_pink",
            "bv_458_burgundy",
            "bv_458_cardinal",
            "bv_458_dark_green",
            "bv_458_gold",
            "bv_458_green",
            "bv_458_grey",
            "bv_458_lavender",
            "bv_458_light_blue",
            "bv_458_light_yellow",
            "bv_458_lime",
            "bv_458_marina_blue",
            "bv_458_navy_blue",
            "bv_458_orange",
            "bv_458_pink",
            "bv_458_purple",
            "bv_458_red",
            "bv_458_sand",
            "bv_458_silver",
            "bv_458_skin_blue",
            "bv_458_skin_camo",
            "bv_458_skin_camo_urban",
            "bv_ben_dover_black2",
            "bv_ben_dover_aqua",
            "bv_ben_dover_baby_blue",
            "bv_ben_dover_baby_pink",
            "bv_ben_dover_burgundy",
            "bv_ben_dover_cardinal",
            "bv_ben_dover_dark_green",
            "bv_ben_dover_gold",
            "bv_ben_dover_green",
            "bv_ben_dover_grey",
            "bv_ben_dover_lavender",
            "bv_ben_dover_light_blue",
            "bv_ben_dover_light_yellow",
            "bv_ben_dover_lime",
            "bv_ben_dover_marina_blue",
            "bv_ben_dover_navy_blue",
            "bv_ben_dover_orange",
            "bv_ben_dover_pink",
            "bv_ben_dover_purple",
            "bv_ben_dover_red",
            "bv_ben_dover_sand",
            "bv_ben_dover_silver",
            "bv_ben_dover_skin_blue",
            "bv_ben_dover_skin_camo",
            "bv_ben_dover_skin_camo_urban",
            "bv_caressa_gt_black2",
            "bv_caressa_gt_aqua",
            "bv_caressa_gt_baby_blue",
            "bv_caressa_gt_baby_pink",
            "bv_caressa_gt_burgundy",
            "bv_caressa_gt_cardinal",
            "bv_caressa_gt_dark_green",
            "bv_caressa_gt_gold",
            "bv_caressa_gt_green",
            "bv_caressa_gt_grey",
            "bv_caressa_gt_lavender",
            "bv_caressa_gt_light_blue",
            "bv_caressa_gt_light_yellow",
            "bv_caressa_gt_lime",
            "bv_caressa_gt_marina_blue",
            "bv_caressa_gt_navy_blue",
            "bv_caressa_gt_orange",
            "bv_caressa_gt_pink",
            "bv_caressa_gt_purple",
            "bv_caressa_gt_red",
            "bv_caressa_gt_sand",
            "bv_caressa_gt_silver",
            "bv_caressa_gt_skin_blue",
            "bv_caressa_gt_skin_camo",
            "bv_caressa_gt_skin_camo_urban",
            "bv_e60_m5_black2",
            "bv_e60_m5_aqua",
            "bv_e60_m5_baby_blue",
            "bv_e60_m5_baby_pink",
            "bv_e60_m5_burgundy",
            "bv_e60_m5_cardinal",
            "bv_e60_m5_dark_green",
            "bv_e60_m5_gold",
            "bv_e60_m5_green",
            "bv_e60_m5_grey",
            "bv_e60_m5_lavender",
            "bv_e60_m5_light_blue",
            "bv_e60_m5_light_yellow",
            "bv_e60_m5_lime",
            "bv_e60_m5_marina_blue",
            "bv_e60_m5_navy_blue",
            "bv_e60_m5_orange",
            "bv_e60_m5_pink",
            "bv_e60_m5_purple",
            "bv_e60_m5_red",
            "bv_e60_m5_sand",
            "bv_e60_m5_silver",
            "bv_e60_m5_skin_blue",
            "bv_e60_m5_skin_camo",
            "bv_e60_m5_skin_camo_urban",
            "bv_e63_amg_black2",
            "bv_e63_amg_aqua",
            "bv_e63_amg_baby_blue",
            "bv_e63_amg_baby_pink",
            "bv_e63_amg_burgundy",
            "bv_e63_amg_cardinal",
            "bv_e63_amg_dark_green",
            "bv_e63_amg_gold",
            "bv_e63_amg_green",
            "bv_e63_amg_grey",
            "bv_e63_amg_lavender",
            "bv_e63_amg_light_blue",
            "bv_e63_amg_light_yellow",
            "bv_e63_amg_lime",
            "bv_e63_amg_marina_blue",
            "bv_e63_amg_navy_blue",
            "bv_e63_amg_orange",
            "bv_e63_amg_pink",
            "bv_e63_amg_purple",
            "bv_e63_amg_red",
            "bv_e63_amg_sand",
            "bv_e63_amg_silver",
            "bv_e63_amg_skin_blue",
            "bv_e63_amg_skin_camo",
            "bv_e63_amg_skin_camo_urban",
            "bv_gtr_spec_V_black2",
            "bv_gtr_spec_V_aqua",
            "bv_gtr_spec_V_baby_blue",
            "bv_gtr_spec_V_baby_pink",
            "bv_gtr_spec_V_burgundy",
            "bv_gtr_spec_V_cardinal",
            "bv_gtr_spec_V_dark_green",
            "bv_gtr_spec_V_gold",
            "bv_gtr_spec_V_green",
            "bv_gtr_spec_V_grey",
            "bv_gtr_spec_V_lavender",
            "bv_gtr_spec_V_light_blue",
            "bv_gtr_spec_V_light_yellow",
            "bv_gtr_spec_V_lime",
            "bv_gtr_spec_V_marina_blue",
            "bv_gtr_spec_V_navy_blue",
            "bv_gtr_spec_V_orange",
            "bv_gtr_spec_V_pink",
            "bv_gtr_spec_V_purple",
            "bv_gtr_spec_V_red",
            "bv_gtr_spec_V_sand",
            "bv_gtr_spec_V_silver",
            "bv_gtr_spec_V_skin_blue",
            "bv_gtr_spec_V_skin_camo",
            "bv_gtr_spec_V_skin_camo_urban",
            "bv_shelly_bf_skin",
            "bv_shelly_bw_skin",
            "bv_shelly_rw_skin",
            "bv_shelly_wb_skin",
            "bv_shelly_wbl_skin",
            "bv_shelly_wf_skin",
            "bv_the_crowner_black2",
            "bv_the_crowner_aqua",
            "bv_the_crowner_baby_blue",
            "bv_the_crowner_baby_pink",
            "bv_the_crowner_burgundy",
            "bv_the_crowner_cardinal",
            "bv_the_crowner_dark_green",
            "bv_the_crowner_gold",
            "bv_the_crowner_green",
            "bv_the_crowner_grey",
            "bv_the_crowner_lavender",
            "bv_the_crowner_light_blue",
            "bv_the_crowner_light_yellow",
            "bv_the_crowner_lime",
            "bv_the_crowner_marina_blue",
            "bv_the_crowner_navy_blue",
            "bv_the_crowner_orange",
            "bv_the_crowner_pink",
            "bv_the_crowner_purple",
            "bv_the_crowner_red",
            "bv_the_crowner_sand",
            "bv_the_crowner_silver",
            "bv_the_crowner_skin_blue",
            "bv_the_crowner_skin_camo",
            "bv_the_crowner_skin_camo_urban",
            "bv_the_crowner_skin_white",
            "bv_monster_black2",
            "bv_monster_aqua",
            "bv_monster_baby_blue",
            "bv_monster_baby_pink",
            "bv_monster_burgundy",
            "bv_monster_cardinal",
            "bv_monster_dark_green",
            "bv_monster_gold",
            "bv_monster_green",
            "bv_monster_grey",
            "bv_monster_lavender",
            "bv_monster_light_blue",
            "bv_monster_light_yellow",
            "bv_monster_lime",
            "bv_monster_marina_blue",
            "bv_monster_navy_blue",
            "bv_monster_orange",
            "bv_monster_pink",
            "bv_monster_purple",
            "bv_monster_red",
            "bv_monster_sand",
            "bv_monster_silver",
            "bv_monster_skin_blue",
            "bv_monster_skin_camo",
            "bv_monster_skin_camo_urban"
];


/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/

/**
 * List of class names of helicopters which can lift objects.
 * Liste des noms de classes des hélicoptères pouvant héliporter des objets.
 */
R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
	
];

/**
 * List of class names of objects which can be lifted.
 * Liste des noms de classes des objets héliportables.
 */
R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	"FMP_Hunter_Ocamo",
            "FMP_Hunter_Skull",
            "FMP_Hunter_Savage",
            "FMP_Hunter_Alpha",
            "FMP_Hunter_Suba",
            "FMP_Hunter_Milsim",
            "FMP_Hunter_Grunge",
            "FMP_Hunter_Bgcamo",
            "FMP_Strider_Splatter",
            "FMP_Strider_Carbon",
            "FMP_Strider_Radioactive",
            "FMP_Strider_Rusty",
            "FMP_Strider_Multi",
            "FMP_Strider_Hex",
            "FMP_Strider_Standard",
            "bv_458_black2",
            "bv_458_aqua",
            "bv_458_baby_blue",
            "bv_458_baby_pink",
            "bv_458_burgundy",
            "bv_458_cardinal",
            "bv_458_dark_green",
            "bv_458_gold",
            "bv_458_green",
            "bv_458_grey",
            "bv_458_lavender",
            "bv_458_light_blue",
            "bv_458_light_yellow",
            "bv_458_lime",
            "bv_458_marina_blue",
            "bv_458_navy_blue",
            "bv_458_orange",
            "bv_458_pink",
            "bv_458_purple",
            "bv_458_red",
            "bv_458_sand",
            "bv_458_silver",
            "bv_458_skin_blue",
            "bv_458_skin_camo",
            "bv_458_skin_camo_urban",
            "bv_ben_dover_black2",
            "bv_ben_dover_aqua",
            "bv_ben_dover_baby_blue",
            "bv_ben_dover_baby_pink",
            "bv_ben_dover_burgundy",
            "bv_ben_dover_cardinal",
            "bv_ben_dover_dark_green",
            "bv_ben_dover_gold",
            "bv_ben_dover_green",
            "bv_ben_dover_grey",
            "bv_ben_dover_lavender",
            "bv_ben_dover_light_blue",
            "bv_ben_dover_light_yellow",
            "bv_ben_dover_lime",
            "bv_ben_dover_marina_blue",
            "bv_ben_dover_navy_blue",
            "bv_ben_dover_orange",
            "bv_ben_dover_pink",
            "bv_ben_dover_purple",
            "bv_ben_dover_red",
            "bv_ben_dover_sand",
            "bv_ben_dover_silver",
            "bv_ben_dover_skin_blue",
            "bv_ben_dover_skin_camo",
            "bv_ben_dover_skin_camo_urban",
            "bv_caressa_gt_black2",
            "bv_caressa_gt_aqua",
            "bv_caressa_gt_baby_blue",
            "bv_caressa_gt_baby_pink",
            "bv_caressa_gt_burgundy",
            "bv_caressa_gt_cardinal",
            "bv_caressa_gt_dark_green",
            "bv_caressa_gt_gold",
            "bv_caressa_gt_green",
            "bv_caressa_gt_grey",
            "bv_caressa_gt_lavender",
            "bv_caressa_gt_light_blue",
            "bv_caressa_gt_light_yellow",
            "bv_caressa_gt_lime",
            "bv_caressa_gt_marina_blue",
            "bv_caressa_gt_navy_blue",
            "bv_caressa_gt_orange",
            "bv_caressa_gt_pink",
            "bv_caressa_gt_purple",
            "bv_caressa_gt_red",
            "bv_caressa_gt_sand",
            "bv_caressa_gt_silver",
            "bv_caressa_gt_skin_blue",
            "bv_caressa_gt_skin_camo",
            "bv_caressa_gt_skin_camo_urban",
            "bv_e60_m5_black2",
            "bv_e60_m5_aqua",
            "bv_e60_m5_baby_blue",
            "bv_e60_m5_baby_pink",
            "bv_e60_m5_burgundy",
            "bv_e60_m5_cardinal",
            "bv_e60_m5_dark_green",
            "bv_e60_m5_gold",
            "bv_e60_m5_green",
            "bv_e60_m5_grey",
            "bv_e60_m5_lavender",
            "bv_e60_m5_light_blue",
            "bv_e60_m5_light_yellow",
            "bv_e60_m5_lime",
            "bv_e60_m5_marina_blue",
            "bv_e60_m5_navy_blue",
            "bv_e60_m5_orange",
            "bv_e60_m5_pink",
            "bv_e60_m5_purple",
            "bv_e60_m5_red",
            "bv_e60_m5_sand",
            "bv_e60_m5_silver",
            "bv_e60_m5_skin_blue",
            "bv_e60_m5_skin_camo",
            "bv_e60_m5_skin_camo_urban",
            "bv_e63_amg_black2",
            "bv_e63_amg_aqua",
            "bv_e63_amg_baby_blue",
            "bv_e63_amg_baby_pink",
            "bv_e63_amg_burgundy",
            "bv_e63_amg_cardinal",
            "bv_e63_amg_dark_green",
            "bv_e63_amg_gold",
            "bv_e63_amg_green",
            "bv_e63_amg_grey",
            "bv_e63_amg_lavender",
            "bv_e63_amg_light_blue",
            "bv_e63_amg_light_yellow",
            "bv_e63_amg_lime",
            "bv_e63_amg_marina_blue",
            "bv_e63_amg_navy_blue",
            "bv_e63_amg_orange",
            "bv_e63_amg_pink",
            "bv_e63_amg_purple",
            "bv_e63_amg_red",
            "bv_e63_amg_sand",
            "bv_e63_amg_silver",
            "bv_e63_amg_skin_blue",
            "bv_e63_amg_skin_camo",
            "bv_e63_amg_skin_camo_urban",
            "bv_gtr_spec_V_black2",
            "bv_gtr_spec_V_aqua",
            "bv_gtr_spec_V_baby_blue",
            "bv_gtr_spec_V_baby_pink",
            "bv_gtr_spec_V_burgundy",
            "bv_gtr_spec_V_cardinal",
            "bv_gtr_spec_V_dark_green",
            "bv_gtr_spec_V_gold",
            "bv_gtr_spec_V_green",
            "bv_gtr_spec_V_grey",
            "bv_gtr_spec_V_lavender",
            "bv_gtr_spec_V_light_blue",
            "bv_gtr_spec_V_light_yellow",
            "bv_gtr_spec_V_lime",
            "bv_gtr_spec_V_marina_blue",
            "bv_gtr_spec_V_navy_blue",
            "bv_gtr_spec_V_orange",
            "bv_gtr_spec_V_pink",
            "bv_gtr_spec_V_purple",
            "bv_gtr_spec_V_red",
            "bv_gtr_spec_V_sand",
            "bv_gtr_spec_V_silver",
            "bv_gtr_spec_V_skin_blue",
            "bv_gtr_spec_V_skin_camo",
            "bv_gtr_spec_V_skin_camo_urban",
            "bv_shelly_bf_skin",
            "bv_shelly_bw_skin",
            "bv_shelly_rw_skin",
            "bv_shelly_wb_skin",
            "bv_shelly_wbl_skin",
            "bv_shelly_wf_skin",
            "bv_the_crowner_black2",
            "bv_the_crowner_aqua",
            "bv_the_crowner_baby_blue",
            "bv_the_crowner_baby_pink",
            "bv_the_crowner_burgundy",
            "bv_the_crowner_cardinal",
            "bv_the_crowner_dark_green",
            "bv_the_crowner_gold",
            "bv_the_crowner_green",
            "bv_the_crowner_grey",
            "bv_the_crowner_lavender",
            "bv_the_crowner_light_blue",
            "bv_the_crowner_light_yellow",
            "bv_the_crowner_lime",
            "bv_the_crowner_marina_blue",
            "bv_the_crowner_navy_blue",
            "bv_the_crowner_orange",
            "bv_the_crowner_pink",
            "bv_the_crowner_purple",
            "bv_the_crowner_red",
            "bv_the_crowner_sand",
            "bv_the_crowner_silver",
            "bv_the_crowner_skin_blue",
            "bv_the_crowner_skin_camo",
            "bv_the_crowner_skin_camo_urban",
            "bv_the_crowner_skin_white",
            "bv_monster_black2",
            "bv_monster_aqua",
            "bv_monster_baby_blue",
            "bv_monster_baby_pink",
            "bv_monster_burgundy",
            "bv_monster_cardinal",
            "bv_monster_dark_green",
            "bv_monster_gold",
            "bv_monster_green",
            "bv_monster_grey",
            "bv_monster_lavender",
            "bv_monster_light_blue",
            "bv_monster_light_yellow",
            "bv_monster_lime",
            "bv_monster_marina_blue",
            "bv_monster_navy_blue",
            "bv_monster_orange",
            "bv_monster_pink",
            "bv_monster_purple",
            "bv_monster_red",
            "bv_monster_sand",
            "bv_monster_silver",
            "bv_monster_skin_blue",
            "bv_monster_skin_camo",
            "bv_monster_skin_camo_urban"
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/

/*
 * This section uses a numeric quantification of capacity and cost of the objets.
 * For example, in a vehicle has a capacity of 100, we will be able to load in 5 objects costing 20 capacity units.
 * The capacity doesn't represent a real volume or weight, but a choice made for gameplay.
 *
 * Note : the priority of a declaration of cost/capacity to another one corresponds to the inverse order in the tables.
 *   It means that the most generic classes should be listed before the less generic classes.
 *   For example : the "Truck_F" class is a child of the "Car_F" class (see http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html).
 *   If "Car_F" is declared before "Truck_F" with a capacity of 40, and "Truck_F" is declared after with a capacity of 140,
 *   Then all the child classes of "Truck_F" will have a capacity of 140.
 *   And all the derived classes of "Car_F", not in "Truck_F", will have a capacity of 40.
 *
 *
 * Cette section utilise une quantification numérique de la capacité et du coût des objets.
 * Par exemple, dans un véhicule d'une capacité de 100, nous pouvons charger 5 objets coûtant 20 unités de capacité.
 * La capacité ne représente ni un poids, ni un volume, mais un choix fait pour la jouabilité.
 *
 * Note : la priorité d'une déclaration de coût/capacité sur une autre correspond à l'ordre inverse dans les tableaux.
 *   Cela implique que les classes les plus génériques doivent être listées avant les classes moins gnériques.
 *   Par exemple : la classe "Truck_F" est une classe dérviée de "Car_F" (voir http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html).
 *   Si "Car_F" est déclaré avant "Truck_F" avec une capacité de 40, et que "Truck_F" est déclaré après avec une capacité de 140,
 *   Alors toutes les classes dérivées de "Truck_F" auront une capacité de 140.
 *   Et toutes les classes dans "Car_F", non présentes dans "Truck_F", auront une capacité de 40.
 */

/**
 * List of class names of vehicles or cargo objects which can transport objects.
 * The second element of the nested arrays is the load capacity (in relation with the capacity cost of the objects).
 *
 * Liste des noms de classes des véhicules ou "objets contenant" pouvant transporter des objets.
 * Le deuxième élément des sous-tableaux est la capacité de chargement (en relation avec le coût de capacité des objets).
 */
R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["FMP_Hunter_Ocamo", 40],
            ["FMP_Hunter_Skull", 40],
            ["FMP_Hunter_Savage", 40],
            ["FMP_Hunter_Alpha", 40],
            ["FMP_Hunter_Suba", 40],
            ["FMP_Hunter_Milsim", 40],
            ["FMP_Hunter_Grunge", 40],
            ["FMP_Hunter_Bgcamo", 40],
            ["FMP_Strider_Splatter", 40],
            ["FMP_Strider_Carbon", 40],
            ["FMP_Strider_Radioactive", 40],
            ["FMP_Strider_Rusty", 40],
            ["FMP_Strider_Multi", 40],
            ["FMP_Strider_Hex", 40],
            ["FMP_Strider_Standard", 40],
            ["bv_458_black2", 40],
            ["bv_458_aqua", 40],
            ["bv_458_baby_blue", 40],
            ["bv_458_baby_pink", 40],
            ["bv_458_burgundy", 40],
            ["bv_458_cardinal", 40],
            ["bv_458_dark_green", 40],
            ["bv_458_gold", 40],
            ["bv_458_green", 40],
            ["bv_458_grey", 40],
            ["bv_458_lavender", 40],
            ["bv_458_light_blue", 40],
            ["bv_458_light_yellow", 40],
            ["bv_458_lime", 40],
            ["bv_458_marina_blue", 40],
            ["bv_458_navy_blue", 40],
            ["bv_458_orange", 40],
            ["bv_458_pink", 40],
            ["bv_458_purple", 40],
            ["bv_458_red", 40],
            ["bv_458_sand", 40],
            ["bv_458_silver", 40],
            ["bv_458_skin_blue", 40],
            ["bv_458_skin_camo", 40],
            ["bv_458_skin_camo_urban", 40],
            ["bv_ben_dover_black2", 40],
            ["bv_ben_dover_aqua", 40],
            ["bv_ben_dover_baby_blue", 40],
            ["bv_ben_dover_baby_pink", 40],
            ["bv_ben_dover_burgundy", 40],
            ["bv_ben_dover_cardinal", 40],
            ["bv_ben_dover_dark_green", 40],
            ["bv_ben_dover_gold", 40],
            ["bv_ben_dover_green", 40],
            ["bv_ben_dover_grey", 40],
            ["bv_ben_dover_lavender", 40],
            ["bv_ben_dover_light_blue", 40],
            ["bv_ben_dover_light_yellow", 40],
            ["bv_ben_dover_lime", 40],
            ["bv_ben_dover_marina_blue", 40],
            ["bv_ben_dover_navy_blue", 40],
            ["bv_ben_dover_orange", 40],
            ["bv_ben_dover_pink", 40],
            ["bv_ben_dover_purple", 40],
            ["bv_ben_dover_red", 40],
            ["bv_ben_dover_sand", 40],
            ["bv_ben_dover_silver", 40],
            ["bv_ben_dover_skin_blue", 40],
            ["bv_ben_dover_skin_camo", 40],
            ["bv_ben_dover_skin_camo_urban", 40],
            ["bv_caressa_gt_black2", 40],
            ["bv_caressa_gt_aqua", 40],
            ["bv_caressa_gt_baby_blue", 40],
            ["bv_caressa_gt_baby_pink", 40],
            ["bv_caressa_gt_burgundy", 40],
            ["bv_caressa_gt_cardinal", 40],
            ["bv_caressa_gt_dark_green", 40],
            ["bv_caressa_gt_gold", 40],
            ["bv_caressa_gt_green", 40],
            ["bv_caressa_gt_grey", 40],
            ["bv_caressa_gt_lavender", 40],
            ["bv_caressa_gt_light_blue", 40],
            ["bv_caressa_gt_light_yellow", 40],
            ["bv_caressa_gt_lime", 40],
            ["bv_caressa_gt_marina_blue", 40],
            ["bv_caressa_gt_navy_blue", 40],
            ["bv_caressa_gt_orange", 40],
            ["bv_caressa_gt_pink", 40],
            ["bv_caressa_gt_purple", 40],
            ["bv_caressa_gt_red", 40],
            ["bv_caressa_gt_sand", 40],
            ["bv_caressa_gt_silver", 40],
            ["bv_caressa_gt_skin_blue", 40],
            ["bv_caressa_gt_skin_camo", 40],
            ["bv_caressa_gt_skin_camo_urban", 40],
            ["bv_e60_m5_black2", 40],
            ["bv_e60_m5_aqua", 40],
            ["bv_e60_m5_baby_blue", 40],
            ["bv_e60_m5_baby_pink", 40],
            ["bv_e60_m5_burgundy", 40],
            ["bv_e60_m5_cardinal", 40],
            ["bv_e60_m5_dark_green", 40],
            ["bv_e60_m5_gold", 40],
            ["bv_e60_m5_green", 40],
            ["bv_e60_m5_grey", 40],
            ["bv_e60_m5_lavender", 40],
            ["bv_e60_m5_light_blue", 40],
            ["bv_e60_m5_light_yellow", 40],
            ["bv_e60_m5_lime", 40],
            ["bv_e60_m5_marina_blue", 40],
            ["bv_e60_m5_navy_blue", 40],
            ["bv_e60_m5_orange", 40],
            ["bv_e60_m5_pink", 40],
            ["bv_e60_m5_purple", 40],
            ["bv_e60_m5_red", 40],
            ["bv_e60_m5_sand", 40],
            ["bv_e60_m5_silver", 40],
            ["bv_e60_m5_skin_blue", 40],
            ["bv_e60_m5_skin_camo", 40],
            ["bv_e60_m5_skin_camo_urban", 40],
            ["bv_e63_amg_black2", 40],
            ["bv_e63_amg_aqua", 40],
            ["bv_e63_amg_baby_blue", 40],
            ["bv_e63_amg_baby_pink", 40],
            ["bv_e63_amg_burgundy", 40],
            ["bv_e63_amg_cardinal", 40],
            ["bv_e63_amg_dark_green", 40],
            ["bv_e63_amg_gold", 40],
            ["bv_e63_amg_green", 40],
            ["bv_e63_amg_grey", 40],
            ["bv_e63_amg_lavender", 40],
            ["bv_e63_amg_light_blue", 40],
            ["bv_e63_amg_light_yellow", 40],
            ["bv_e63_amg_lime", 40],
            ["bv_e63_amg_marina_blue", 40],
            ["bv_e63_amg_navy_blue", 40],
            ["bv_e63_amg_orange", 40],
            ["bv_e63_amg_pink", 40],
            ["bv_e63_amg_purple", 40],
            ["bv_e63_amg_red", 40],
            ["bv_e63_amg_sand", 40],
            ["bv_e63_amg_silver", 40],
            ["bv_e63_amg_skin_blue", 40],
            ["bv_e63_amg_skin_camo", 40],
            ["bv_e63_amg_skin_camo_urban", 40],
            ["bv_gtr_spec_V_black2", 40],
            ["bv_gtr_spec_V_aqua", 40],
            ["bv_gtr_spec_V_baby_blue", 40],
            ["bv_gtr_spec_V_baby_pink", 40],
            ["bv_gtr_spec_V_burgundy", 40],
            ["bv_gtr_spec_V_cardinal", 40],
            ["bv_gtr_spec_V_dark_green", 40],
            ["bv_gtr_spec_V_gold", 40],
            ["bv_gtr_spec_V_green", 40],
            ["bv_gtr_spec_V_grey", 40],
            ["bv_gtr_spec_V_lavender", 40],
            ["bv_gtr_spec_V_light_blue", 40],
            ["bv_gtr_spec_V_light_yellow", 40],
            ["bv_gtr_spec_V_lime", 40],
            ["bv_gtr_spec_V_marina_blue", 40],
            ["bv_gtr_spec_V_navy_blue", 40],
            ["bv_gtr_spec_V_orange", 40],
            ["bv_gtr_spec_V_pink", 40],
            ["bv_gtr_spec_V_purple", 40],
            ["bv_gtr_spec_V_red", 40],
            ["bv_gtr_spec_V_sand", 40],
            ["bv_gtr_spec_V_silver", 40],
            ["bv_gtr_spec_V_skin_blue", 40],
            ["bv_gtr_spec_V_skin_camo", 40],
            ["bv_gtr_spec_V_skin_camo_urban", 40],
            ["bv_shelly_bf_skin", 40],
            ["bv_shelly_bw_skin", 40],
            ["bv_shelly_rw_skin", 40],
            ["bv_shelly_wb_skin", 40],
            ["bv_shelly_wbl_skin", 40],
            ["bv_shelly_wf_skin", 40],
            ["bv_the_crowner_black2", 40],
            ["bv_the_crowner_aqua", 40],
            ["bv_the_crowner_baby_blue", 40],
            ["bv_the_crowner_baby_pink", 40],
            ["bv_the_crowner_burgundy", 40],
            ["bv_the_crowner_cardinal", 40],
            ["bv_the_crowner_dark_green", 40],
            ["bv_the_crowner_gold", 40],
            ["bv_the_crowner_green", 40],
            ["bv_the_crowner_grey", 40],
            ["bv_the_crowner_lavender", 40],
            ["bv_the_crowner_light_blue", 40],
            ["bv_the_crowner_light_yellow", 40],
            ["bv_the_crowner_lime", 40],
            ["bv_the_crowner_marina_blue", 40],
            ["bv_the_crowner_navy_blue", 40],
            ["bv_the_crowner_orange", 40],
            ["bv_the_crowner_pink", 40],
            ["bv_the_crowner_purple", 40],
            ["bv_the_crowner_red", 40],
            ["bv_the_crowner_sand", 40],
            ["bv_the_crowner_silver", 40],
            ["bv_the_crowner_skin_blue", 40],
            ["bv_the_crowner_skin_camo", 40],
            ["bv_the_crowner_skin_camo_urban", 40],
            ["bv_the_crowner_skin_white", 40],
            ["bv_monster_black2", 40],
            ["bv_monster_aqua", 40],
            ["bv_monster_baby_blue", 40],
            ["bv_monster_baby_pink", 40],
            ["bv_monster_burgundy", 40],
            ["bv_monster_cardinal", 40],
            ["bv_monster_dark_green", 40],
            ["bv_monster_gold", 40],
            ["bv_monster_green", 40],
            ["bv_monster_grey", 40],
            ["bv_monster_lavender", 40],
            ["bv_monster_light_blue", 40],
            ["bv_monster_light_yellow", 40],
            ["bv_monster_lime", 40],
            ["bv_monster_marina_blue", 40],
            ["bv_monster_navy_blue", 40],
            ["bv_monster_orange", 40],
            ["bv_monster_pink", 40],
            ["bv_monster_purple", 40],
            ["bv_monster_red", 40],
            ["bv_monster_sand", 40],
            ["bv_monster_silver", 40],
            ["bv_monster_skin_blue", 40],
            ["bv_monster_skin_camo", 40],
            ["bv_monster_skin_camo_urban", 40]
];

/**
 * List of class names of objects which can be loaded in transport vehicle/cargo.
 * The second element of the nested arrays is the cost capacity (in relation with the capacity of the vehicles).
 *
 * Liste des noms de classes des objets transportables.
 * Le deuxième élément des sous-tableaux est le coût de capacité (en relation avec la capacité des véhicules).
 */
R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	// e.g. : ["MyTransportableObjectClassName1", itsCost], ["MyTransportableObjectClassName2", itsCost]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

/**
 * List of class names of objects which can be carried and moved by a player.
 * Liste des noms de classes des objets qui peuvent être portés et déplacés par le joueur.
 */
R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	// e.g. : "MyMovableObjectClassName1", "MyMovableObjectClassName2"
];
