R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
	"truck_01_base_f",
	"truck_02_base_f",
	"truck_03_base_f",
	"b_apc_tracked_01_crv_f",
	"Offroad_01_repair_base_F",
	"B_Truck_01_transport_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_box_F",
			"B_Truck_01_Repair_F", 
			"B_Truck_01_ammo_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F", 
			"B_G_Van_01_transport_F", 
			"B_G_Van_01_fuel_F",
			"O_G_Offroad_01_repair_F", 
			"O_G_Offroad_01_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_transport_F", 
			"O_Truck_03_transport_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F", 
			"O_Truck_03_device_F",
			"O_Truck_02_box_F",
			"O_Truck_02_medical_F", 
			"O_Truck_02_Ammo_F",
			"O_Truck_02_fuel_F",
			"O_G_Van_01_transport_F",
			"O_G_Van_01_fuel_F",
			"I_G_Offroad_01_F",
			"I_G_Offroad_01_armed_F", 
			"I_Truck_02_transport_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_medical_F", 
			"I_Truck_02_fuel_F",
			"I_G_Van_01_transport_F", 
			"I_G_Van_01_fuel_F",
			"B_G_Offroad_01_armed_F", 
			"O_G_Offroad_01_armed_F",
			"B_MRAP_01_gmg_F", 
			"B_MRAP_01_hmg_F",
			"O_MRAP_02_gmg_F",  
			"O_MRAP_02_hmg_F",
			"I_MRAP_03_hmg_F", 
			"I_MRAP_03_gmg_F",
			"B_APC_Wheeled_01_cannon_F", 			
			"I_APC_Wheeled_03_cannon_F",
			"B_APC_Tracked_01_rcws_F",
			"B_APC_Tracked_01_CRV_F",
			"B_APC_Tracked_01_AA_F",
			"B_MBT_01_arty_F",
			"B_MBT_01_mlrs_F",
			"B_MBT_01_TUSK_F",
			"O_APC_Tracked_02_cannon_F", 
			"O_APC_Tracked_02_AA_F",
			"O_MBT_02_cannon_F",
			"O_MBT_02_arty_F",
			"O_APC_Wheeled_02_rcws_F", 
			"I_APC_tracked_03_cannon_F",
			"I_MBT_03_cannon_F"
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
	"truck_01_base_f",
	"truck_02_base_f",
	"truck_03_base_f",
	"b_apc_tracked_01_crv_f",
	"Offroad_01_repair_base_F",
	"B_Truck_01_transport_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_box_F",
			"B_Truck_01_Repair_F", 
			"B_Truck_01_ammo_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F", 
			"B_G_Van_01_transport_F", 
			"B_G_Van_01_fuel_F",
			"O_G_Offroad_01_repair_F", 
			"O_G_Offroad_01_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_transport_F", 
			"O_Truck_03_transport_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F", 
			"O_Truck_03_device_F",
			"O_Truck_02_box_F",
			"O_Truck_02_medical_F", 
			"O_Truck_02_Ammo_F",
			"O_Truck_02_fuel_F",
			"O_G_Van_01_transport_F",
			"O_G_Van_01_fuel_F",
			"I_G_Offroad_01_F",
			"I_G_Offroad_01_armed_F", 
			"I_Truck_02_transport_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_medical_F", 
			"I_Truck_02_fuel_F",
			"I_G_Van_01_transport_F", 
			"I_G_Van_01_fuel_F",
			"B_G_Offroad_01_armed_F", 
			"O_G_Offroad_01_armed_F",
			"B_MRAP_01_gmg_F", 
			"B_MRAP_01_hmg_F",
			"O_MRAP_02_gmg_F",  
			"O_MRAP_02_hmg_F",
			"I_MRAP_03_hmg_F", 
			"I_MRAP_03_gmg_F",
			"B_APC_Wheeled_01_cannon_F", 			
			"I_APC_Wheeled_03_cannon_F",
			"B_APC_Tracked_01_rcws_F",
			"B_APC_Tracked_01_CRV_F",
			"B_APC_Tracked_01_AA_F",
			"B_MBT_01_arty_F",
			"B_MBT_01_mlrs_F",
			"B_MBT_01_TUSK_F",
			"O_APC_Tracked_02_cannon_F", 
			"O_APC_Tracked_02_AA_F",
			"O_MBT_02_cannon_F",
			"O_MBT_02_arty_F",
			"O_APC_Wheeled_02_rcws_F", 
			"I_APC_tracked_03_cannon_F",
			"I_MBT_03_cannon_F"
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
"truck_01_base_f",
	"truck_02_base_f",
	"truck_03_base_f",
	"b_apc_tracked_01_crv_f",
	"Offroad_01_repair_base_F",
	"B_Truck_01_transport_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_box_F",
			"B_Truck_01_Repair_F", 
			"B_Truck_01_ammo_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F", 
			"B_G_Van_01_transport_F", 
			"B_G_Van_01_fuel_F",
			"O_G_Offroad_01_repair_F", 
			"O_G_Offroad_01_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_transport_F", 
			"O_Truck_03_transport_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F", 
			"O_Truck_03_device_F",
			"O_Truck_02_box_F",
			"O_Truck_02_medical_F", 
			"O_Truck_02_Ammo_F",
			"O_Truck_02_fuel_F",
			"O_G_Van_01_transport_F",
			"O_G_Van_01_fuel_F",
			"I_G_Offroad_01_F",
			"I_G_Offroad_01_armed_F", 
			"I_Truck_02_transport_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_medical_F", 
			"I_Truck_02_fuel_F",
			"I_G_Van_01_transport_F", 
			"I_G_Van_01_fuel_F",
			"B_G_Offroad_01_armed_F", 
			"O_G_Offroad_01_armed_F",
			"B_MRAP_01_gmg_F", 
			"B_MRAP_01_hmg_F",
			"O_MRAP_02_gmg_F",  
			"O_MRAP_02_hmg_F",
			"I_MRAP_03_hmg_F", 
			"I_MRAP_03_gmg_F",
			"B_APC_Wheeled_01_cannon_F", 			
			"I_APC_Wheeled_03_cannon_F",
			"B_APC_Tracked_01_rcws_F",
			"B_APC_Tracked_01_CRV_F",
			"B_APC_Tracked_01_AA_F",
			"B_MBT_01_arty_F",
			"B_MBT_01_mlrs_F",
			"B_MBT_01_TUSK_F",
			"O_APC_Tracked_02_cannon_F", 
			"O_APC_Tracked_02_AA_F",
			"O_MBT_02_cannon_F",
			"O_MBT_02_arty_F",
			"O_APC_Wheeled_02_rcws_F", 
			"I_APC_tracked_03_cannon_F",
			"I_MBT_03_cannon_F"
	
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["tank", 5],
	["car", 6],
	["motorcycle", 2],
	["truck_f", 100],
	["bus", 30],
	["kart_01_base_f", 2],
	["mrap_01_base_f", 12],
	["mrap_02_base_f", 12],
	["mrap_03_base_f", 12],
	["offroad_01_base_f", 10],
	["offroad_01_armed_base_f", 4],
	["quadbike_01_base_f", 3],
	["quadbike_base_f", 3],
	["b_truck_01_mover_f", 5],
	["b_truck_01_repair_f", 170],
	["b_truck_01_covered_f", 120],
	["b_truck_01_ammo_f", 120],
	["b_truck_01_box_f", 170],
	["truck_02_base_f", 120],
	["i_truck_02_medical_f", 100],
	["i_truck_02_fuel_f", 5],
	["i_truck_02_transport_f", 100],
	["o_truck_02_fuel_f", 5],
	["o_truck_02_transport_f", 100],
	["o_truck_03_ammo_f", 140],
	["o_truck_03_device_f", 5],
	["o_truck_03_fuel_f", 5],
	["van_01_base_f", 5],
	["c_van_01_box_f", 40],
	["c_van_01_transport_f", 25],
	["i_g_van_01_transport_f", 25],
	["wheeled_apc_f", 10]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	["kart_01_base_f", 40],
	["quadbike_01_base_f", 40],
	["ugv_01_base_f", 100]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
];